### ISSUE TITLE
[SUGGESTION] Be by default as strict as possible

### ISSUE THREAD

**Issue by redradist** [hsutter/cppfront#110]
As was suggested on [Can C++ be 10x Simpler & Safer? - Herb Sutter - CppCon 2022](https://www.youtube.com/watch?v=ELeZAKCN4tY&list=PLHTh1InhhwT6c2JNtUiJkaH8YRqzhU7Ag&index=51&t=2383s) in QA session, to use all strict features by default:
1) Do all bounds checking by default and allow alternative --allow-unbound-index-operator
2) Allow only by default cpp2 syntax and instead add flag --allow-mixed-mode
3) ... and others

It is not harder to use flags to allow current C++ behavior instead of allowing "safe" behavior. I mean if user want to use current C++ behavior then a new flag that relax all restriction could be introduced

**Will your feature suggestion eliminate X% of security vulnerabilities of a given kind in current C++ code?**
Yes, because it will enforce users to write code "safe" code and to ask to write "unsafe" code.
Also, whenever user will want to write "unsafe" code, it will appear in code review

**Will your feature suggestion eliminate X% of current C++ guidance literature?"**
Should be calculated :)

**Comment by aminya** [comment]
I agree with this. I think the defaults should enable the pure and the bound checks modes. Only if someone needs mixed or unsafe code, they might opt out by passing a flag or using a contract. 

Doing it the reverse reminds me of the compilers not enabling warnings and requiring manual passing of [-Wall -Wextra -Wpedantic, and all the other Ws](https://github.com/aminya/project_options/blob/main/src/CompilerWarnings.cmake)! 

Currently, ensuring the safety of the language also requires checking the correctness of the whole build system because they might not pass `-p` somewhere.

**Comment by fluffychaos** [comment]
This also increases confidence in the code compiling without warnings to behave correctly. By having all these safety checks enabled by default the mental burden is moved from the developer to the compiler. Once your code compiles a lot of potential sources of runtime errors are already eliminated or are no longer silent errors like out-of-bounds accesses can easily be. 

As it got already pointed out, people can easily not think about many aspects of their code, like the actual lifetime of their objects, correct indices etc. If, however, you have to explicitly disable a safety feature you have ti think about it beforehand. Otherwise you would not come to the conclusion that you have to deactivate it.

It makes writing good code easier while potentially bad code becomes harder to write as you have to go this extra step asking you to be aware of what you are doing.

While you could have compiler flags to turn these safety checks off it may also be worth thinking about having a form of Rusts `unsafe` language construct so you can disable these checks just for a certain region of code. Tools can then detect these regions and apply a more relaxed set of rules there, like allowing pointer arithmetic. This way these regions without the safety checks become more localized.

**Comment by JohelEGP** [comment]
I mostly agree, but see https://github.com/hsutter/cppfront/wiki/Design-note:-Unsafe-code for the last part.

> While you could have compiler flags to turn these safety checks off it may also be worth thinking about having a form of Rusts `unsafe` language construct so you can disable these checks just for a certain region of code. Tools can then detect these regions and apply a more relaxed set of rules there, like allowing pointer arithmetic. This way these regions without the safety checks become more localized.

**Comment by fluffychaos** [comment]
Ah, thanks of showing me that. His position certainly is a good one. Making the kind of safety-feature-suppression explicit should further help with forcing you to make your intent clear.

> I mostly agree, but see https://github.com/hsutter/cppfront/wiki/Design-note:-Unsafe-code for the last part.

**Comment by hsutter** [comment]
Hmm... are you maybe wanting something like a single `-strict-cpp2` switch that is equivalent to 

    -p[ure-cpp2]        Allow Cpp2 syntax only
    -n[ull-checks]      Enable null safety contract checks
    -s[ubscript-checks] Enable subscript bounds safety contract checks

?

**Comment by aminya** [comment]
> One concern I have about making the null and subscript checks on by default and rely on opt-out is that, should there be some minor overhead, people will start a meme that "Cpp2 is slow" without context

Well, if Cpp2 is not as strict by default, some people will say "Cpp2 is not safe" or "Cpp2 doesn't solve anything". Such a minor overhead should not be a concern! Rust has runtime `unwraps` everywhere and no one ever has said that Rust is slow.

**Comment by redradist** [comment]
@hsutter 
> Hmm... are you maybe wanting something like a single `-strict-cpp2` switch that is equivalent to
> 
> ```
> -p[ure-cpp2]        Allow Cpp2 syntax only
> -n[ull-checks]      Enable null safety contract checks
> -s[ubscript-checks] Enable subscript bounds safety contract checks
> ```
> 
> ?
> 
> One concern I have about making the null and subscript checks on by default and rely on opt-out is that, should there be some minor overhead, people will start a meme that "Cpp2 is slow" without context. That has happened with C++. Making them off by default and opt-in helps reduce the chances of that misunderstanding/misinformation, and also feels like it hews more closely to C++'s core philosophy that we shouldn't pay for something unless we use it.

Yes, the suggestion is to solve fundamental C++ issue - "safety", like Rust did !!
Rust has a bound checks all over the place as @aminya said !!

C++ - if you do not use something you do not pay for it, but if you use it you pay for it.

In Cpp2, we use a "safety" feature and we pay for it !! If we do not want to pay for it, we need to say compiler about it and Cpp2 will have the same "safety" as Cpp1

**Comment by aminya** [comment]
A survey on the actual effect of the Rust bounds checks in a real-world application. The conclusion is that the performance effect is negligible and sometimes it results in improvements by unlocking optimizations!
https://blog.readyset.io/bounds-checks/

**Comment by hsutter** [comment]
Thanks! After thinking this over, I've decided to enable `-null-check` and `-subscript-checks` by default, and enable opt-out with a `-` suffix (e.g., `-null-checks-` or `-n-`).

Closed by this commit: 1a0967408f7de880183a329b1bb5bad30b59cb65
