### ISSUE TITLE
[BUG] constexpr initialization for std::array

### ISSUE THREAD

**Issue by MaxSagebaum** [hsutter/cppfront#1104]
It seems that constexpr initalization is generated the wrong way.

```
var : std::array<char, 5> == "abcd";
```
is lowered to
```
std::array<char,5> constexpr var = "abcd";
```
which results into the error:
```
main.cpp2:8:34: error: no viable conversion from 'const char[5]' to 'const std::array<char, 5>'
```

The correct lowering in this case would be:
```
std::array<char, 5> constexpr var {"abcd"};
```
this version, without the `constexpr`, is used for `var : std::array<char, 5> = "abcd";`.

Reproducer:
https://cpp2.godbolt.org/z/KbPvxPdoq

**Comment by bluetarpmedia** [comment]
I'm not sure if converting from a string literal `"abcd"` to `std::array<char>` is intentionally supported or not. My guess is this syntax for non-constexpr init:
```cpp
var2 : std::array<char, 5> = "abcd";
```
Only happens to work because of the cppfront rules of turning that into `{"abcd"}`.

But I think the Cpp2 idiom for initialising a `std::array<char>` is:
```cpp
var1 : std::array<char, 5> =  ('a', 'b', 'c', 'd');
var2 : std::array<char, 5> == ('a', 'b', 'c', 'd');  // constexpr
```
That second `var2` line lowers to:
```cpp
std::array<char,5> constexpr var2{ 'a', 'b', 'c', 'd' };
```

**Comment by hsutter** [comment]
Thanks!

> only happens to work because of the cppfront rules of turning that into `{"abcd"}`.

Then `==` should be consistent with that, I think. Fixing...

**Comment by MaxSagebaum** [comment]
Thanks.
