### ISSUE TITLE
[SUGGESTION] Permissive License

### ISSUE THREAD

**Issue by sisakat** [hsutter/cppfront#122]
The project is currently licensed under `CC-BY-NC-ND-4.0`. This license is not really friendly with open-source, as it does not allow derivatives. So any modification made to the code cannot be published to the public, hence forking the repository and making changes is not even possible. At least as far as I can understand the terms here [https://creativecommons.org/licenses/by-nc-nd/4.0/](https://creativecommons.org/licenses/by-nc-nd/4.0/).

I would like to suggest to use a more permissive license that actually encourages contribution/experiments.

**Comment by switch-blade-stuff** [comment]
While the end licensing decision is up to Herb, I would also like to add that I have come across some people being wary of CC licenses due to them being mostly aimed at non-software creative work, and as such not being entirely applicable for software projects.

**Comment by hsutter** [comment]
Yes, I intend to make the license permissive later if this develops into something usable, but not yet while it's still very much a personal experiment.

At this early incomplete state, I deliberately chose a non-permissive license so that I could open-source the code but avoid two pitfalls:
- I want to be clear it's a personal experiment only, and not for production use.
- I want to not enable a proliferation of forks while I'm still incubating this. If someone is inspired by this then that's great, and I encourage them to do the same thing I did and create their own experimental project and let us know the results!

That said, this license does encourage contributions, and there is a CLA. Speaking of contributions, I have a set of PRs waiting for me now that I've partly recovered and un-submerged from [running our first ISO C++ meeting in almost three years](https://github.com/hsutter/cppfront/pull/106#issuecomment-1299365791). :)

However, down the road if anything does come of this project and it becomes suitable for some use in production, then I'd change the license to a mainstream OSS license, possibly Apache with LLVM exception which is one of the most popular now for that kind of project, or whatever is the most popular and appropriate license at the time I decide it's something worth actually "shipping."

Thanks for your interest in the project!

**Comment by neeraj9** [comment]
Great keynote @hsutter in CppConn 2022 and I agree with you that C++ engineers should come back to the language which they loved and help it flourish. I have been a C / C++ fanboy for decades and understand all the legacy challenges. This is an ambitious attempt, but much needed to help the language. In my opinion, a lot of C++ engineers feel the pain and lesser friction would help grow the project.

With due respect, the decision is ultimately yours. It is just my humble opinion on this topic.

Thanks for sharing this with the world.
