### ISSUE TITLE
[BUG] Definite last use and lvalue reference constructor generates wrong code?

### ISSUE THREAD

**Issue by germandiagogomez** [hsutter/cppfront#1228]
**Describe the bug**

It seems that a move is performed when binding to an lvalue reference from a C++ API: concretely, the API is stream_iterator, here (constructor number 3):

https://en.cppreference.com/w/cpp/iterator/istream_iterator/istream_iterator

**To Reproduce**

```
read_words: (p: std::filesystem::path, 
             inout stats: CountWordsStats,
             read_buf_size: int) -> std::vector<std::string> = {
  using namespace std;
  result := std::vector<std::string>();
  dyn_buf := std::make_unique_for_overwrite<char[]>(read_buf_size);
  file_stream : std::ifstream = ();
  if read_buf_size != 4096 {
     file_stream.rdbuf()*.pubsetbuf(std::addressof(dyn_buf[0]), read_buf_size);
  }
  file_stream.open(p.c_str());
  if !file_stream.is_open() {
     return ();
  }
  file_stream.seekg(0, std::ios::end);
  file_stream_size := file_stream.tellg();
  file_stream.seekg(0, std::ios::beg);
  stats.bytes_read += file_stream_size;
  
  // This is translated via a cpp2::move(file_stream),
  // which does not bind to an lvalue reference constructor.
  strIt := std::istream_iterator<std::string>(file_stream);
  eof := std::istream_iterator<std::string>();

  // ...
  return result;
}
```

**Additional context**

I I add `file_stream.seekg(...)` after the istream_iterator construction, then things work correctly.

**Comment by hsutter** [comment]
Good question! The issue is that the last use of the object is to a modifiable parameter (Cpp1 `&`, Cpp2 `inout`) and so the function call can modify the parameter and the last use is never subsequently used. So you need to add `_ = file_stream;` to explicitly discard the value. The documentation for this is here: [Function outputs are not implicitly discardable](https://hsutter.github.io/cppfront/cpp2/functions/?h=discard#function-outputs-are-not-implicitly-discardable).

We give a useful error message for this if the function call uses [UFCS, unified function call syntax](https://hsutter.github.io/cppfront/cpp2/expressions/?h=ufcs#calling-functions-fx-syntax-xf-ufcs-syntax-and-xf-members-only-syntax) (e.g., `obj.func()`) but not if the function call uses ordinary function call syntax (e.g., `func(obj)`).

Here's a distilled example, changing the iterator construction function call to use UFCS syntax:

```cpp
read_words: () = {
  fs : std::ifstream = ();
  // ...
  strIt := fs.std::istream_iterator<std::string>();  // nice error message
  // ... no further use of fs ...
}
```

This generates the static_assert failure message: `error: implicit discard of an object's modified value is not allowed - this function call modifies 'obj', but 'obj' is never used again in the function so the new value is never used - if that's what you intended, add another line '_ = obj;' afterward to explicitly discard the new value of the object`.

So the solution is to add this line later on:

```cpp
  _ = fs;  // explicitly discard 'out' value of 'fs'
```

I think this has value, because the state of `fs` really has changed because we're now further along in the stream, and it could well be intended that more be read from the stream (either locally, or maybe it was intended to be returned, or otherwise handed off somewhere). Making the discard explicit self-documents that we know there's a state change and we don't care about it.

But you didn't get this message because currently cppfront doesn't generate a `static_assert` to check for `func(obj)` regular function call syntax:

```cpp
  strIt := std::istream_iterator<std::string>(fs);  // no static_assert, sorry
```

or if you'd written the usual declaration syntax:

```cpp
  strIt: std::istream_iterator<std::string> = (fs);  // no static_assert, sorry
```

so at the moment you just have to know that the problem is that you have to discard the value.

All of these are solved by adding this explicit discard line anywhere afterwards, so that this becomes the last use of the variable:

```cpp
  _ = fs;  // explicitly discard 'out' value of 'fs', solves all the above variations
```

I'd like to generate the error also for the other cases, but I don't know how to do that without turning every ordinary function call, and every expression that contains a last use, into a lambda as we do with UFCS. Because in general the last use can be in a function call or initializer that's inside a subexpression of a more-complex expression, and the only way I know to inject a check into expression scope is to put it in a lambda. I'm open to ideas... my hope is that people new to Cpp2 will encounter this a handful of times and quickly learn 'oh that's what this is, I need to discard the modified value if I don't want to use it.'

Thanks for the question! If this doesn't fully answer your question, please reopen.

**Comment by germandiagogomez** [comment]
Hello Herb Sutter,

This definitely answers my question. I just thought it was a bug but indeed the section for inout clarifies, it was just that it looked weird to me, but as you mention, this makes things explicit and inout is not discarded.

So everything's clear. Thanks!
