### ISSUE TITLE
[QUESTION]  will Cpp2 in/inout/out parameters honor the law of exclusivity? (Related to C++ safe subsets)

### ISSUE THREAD

**Issue by germandiagogomez** [hsutter/cppfront#1289]
Hello there.

I am a person inclined towards value semantics in my programs when possible.

I would like to ask (current Cpp2 implementation apart) if the parameter passing in Cpp has a vocation for implementing the law of exclusivity meaning that many in parameters can access the same data but no inout/out can or writing the variable is allowed.

I have been following with interest some talks and I am referring to the fact of being able to avoid problems like this: https://youtu.be/QthAU-t3PQ4?t=535

Namely, there would be analysis for exclusivity: when an in parameter is there, several of them are possible. When an out or inout parameter is then access should be exclusive. If there is an inout/out parameter, then in parameters are not possible.

I think it would be worth an analysis if that could be implemented.

**Comment by dutkalex** [comment]
A similar discussion was brought up in #1273

> I think it would be worth an analysis if that could be implemented.
If I recall correctly, whether it is implementable is tricky and there is no consensus right now on the subject

**Comment by germandiagogomez** [comment]
> If I recall correctly, whether it is implementable is a tricky question because cpp2 is not all-in on value semantics as is val/hylo, and there is no consensus right now on the subject

I think it is not implementable in C++ (right now) but it should be as an "overlay analysis" on Cpp2 as long as you guarantee that your code is not mixed back with regular C++.

Namely, if you translate it to references that have been verified by the upper Cpp2 layer and not mix it then it is ok, otherwise you are on your own.

**Comment by nicoheidtke** [comment]
Opinion: 
In my personal experience, inout and out parameters are pretty much not needed at all. 
I've been using them very sparingly for a decade now and pretty much stopped using them at all for many years now, As illustrated, they are dangerous and confusing and have been routinely abused to craft bad APIs.
It has been one of those things we teach new developers to avoid for a long time.

Luckily, they really aren't needed  that much anymore - thanks to all the improvements wrt RVO.

Thus, I'd think I'd rather have these removed or at least deprecated in cpp2 in order to reduce the complexity and the teaching required for cpp2 even further.

**Comment by dutkalex** [comment]
> Thus, I'd think I'd rather have these removed or at least deprecated in cpp2 in order to reduce the complexity and the teaching required for cpp2 even further.

I understand where you're coming from and I do agree that, where possible, moving out params to the return type eliminates the problem, on top of being more readable. I don't think however that we can reasonably get rid of out and inout parameters, as this would create issues on other fronts:
- The whole delegating constructor generalization through out params proposed by Herb to ensure initialization safety is very valuable IMO, and without out params we would have to revert to "no uninitialized variables" to ensure the same guarantees, which would be against the "don't pay for what you don't use" principle
- For example, it is common to try to minimize allocations for performance reasons, and I don't see how we could write stuff like this without out params:
```cpp
auto buffer = std::make_unique<int[]>( big_enough_value );
for ( auto chunk : data ){
  init_buffer( buffer, data );
  do_some_stuff( buffer );
}
```

**Comment by germandiagogomez** [comment]
> In my personal experience, inout and out parameters are pretty much not needed at all.
> I've been using them very sparingly for a decade now and pretty much stopped using them at all for many years now, As illustrated, they are dangerous and confusing and have been routinely abused to craft bad APIs.
> It has been one of those things we teach new developers to avoid for a long time.

There are legit reasons to use out and inout parameters sometimes. Compare this:

```
func: (a : int, b: int): std::unique_ptr<MyType>  = {
   //...
   auto t = std::make_unique<MyType>();
   return t;
}
```

To this:

```
MyType t;
func: (a : int, b: int, out t: MyType): std::unique_ptr<MyType>  = {
   //...
   t = MyType;
   return t;
}
```

In the second form, since you create MyType outside, it is easy to customize allocation.

This happens, for example between dll boundaries in Windows, where the heap (at least before) used to pose some problems if you allocated in one dll and released from the other.

I would favor returning things through its return channels, no wonder, most of the time. But once you create things inside your function, if the function allocates, it is not possible to control allocation anymore.

**Comment by nicoheidtke** [comment]
> The whole delegating constructor generalization through out params proposed by Herb...

I haven't looked into the "delegating constructor generalization through out parameters proposed by Herb" yet. Will do so.

> For example, it is common to try to minimize allocations for performance reasons, and I don't see how we could write stuff like this without out params...

I'm very aware that one often has to resort to those tactics when dealing with C interfaces or low-level memory manipulation. But beyond that the utility of out parameters is very slim to non-existant.
I've found that nicely wrapping/abstracting these few ugly parts allows me to avoid introducing these bad patterns anywhere else.
And that means I have to wonder if cpp2 actually needs them. I'd personally write those parts in good old C++ and then don't ever touch the in/inout parameters ever in cpp2.
Kind of like the support for "unsafe" code in C# or rust. C++ would be the "unsafe" dialect of cpp2. Or heck, better just stick to C.

> There are legit reasons to use out and inout parameters sometimes. Compare this...

Actually, the first form is typically exactly what you want precisely because of DLL boundaries (if you need to worry about that at all, that is):
If that matters, the more common scenario is that you want to allocate objects that the library provides from inside the library (because it might use special runtime, allocators or STL implementations etc).

And if you truly want and need to customize allocation from the outside (a library that supports external control of its allocations seems rare nowadays), then the library pretty much HAS to provide an overridable interface to its own allocation mechanisms anyway. And this in turn doesn't need an "out" parameter either.
Otherwise, any internally created object with std::vector or std::map members will destroy your dreams of fully customizing allocations of a library anyway.
I've seen those libraries and I wrote them myself - a long time ago when memory was more scarce and the risks of breaking ABI were much more common.
And to add some precision to what you are saying: On Windows "the heap" doesn't cause any problems, but rather the potentially multiple instances of a VC++ runtime debug heap and ABI differences between the runtime implementations do.
But only if you link different runtimes within the same process - which could easily causes problems for both forms due to potentially different memory layouts of STL objects and padding etc.

If you are in that situation (different runtimes/debug heaps) - which you should avoid if possible - you better also not use anything but trivial/POD types across the library boundary to save yourself some massive headaches.
You could look at how the Windows Kernel API handles ABI compatibility and allocations to get an idea how to design for maximum forward compatibility and ABI stability.

And if you are not in that situation (most people aren't, luckily), then you don't need out parameters (for that reason).

**Comment by germandiagogomez** [comment]
> Kind of like the support for "unsafe" code in C# or rust. C++ would be the "unsafe" dialect of cpp2. Or heck, better just stick to C.

I would say no.

> I'm very aware that one often has to resort to those tactics when dealing with C interfaces or low-level memory manipulation. But beyond that the utility of out parameters is very slim to non-existant.
I've found that nicely wrapping/abstracting these few ugly parts allows me to avoid introducing these bad patterns anywhere else.

And here I would say also no.

Let me explain: being able to go low-level is a characteristic of C++ (should be Cpp2 also, just with better defaults). If you *eliminate* that possibility you are just making some patterns more difficult, for example for embedded device developers where memory allocation is usually tightly controlled. If you eliminate this, you have to resort to way more low-level practices without the analysis that inout would do (for example if the law of exclusivity is added), losing benefit from those safer patterns.

I know it is not as "clean", but if I want clean, I go to Python or something without even pointers or where I cannot control memory allocation directly...

> (a library that supports external control of its allocations seems rare nowadays)

That does not mean it is a useless pattern at all. I found real cases where this is important and if you removed that capacity from C++ it would be quite bad news for some use cases, that, as I said, are totally valid.

>  On Windows "the heap" doesn't cause any problems, but rather the potentially multiple instances of a VC++ runtime debug heap and ABI differences between the runtime implementations do.

Yes, I meant that. But the consequence of that is that you allocate in your boundary, not in the boundaries of your side or an allocation on the other side and a release on your side will bring trouble for you. This is a pattern that can easily appear in APIs with dlls, but it is not the only case.

> If you are in that situation (different runtimes/debug heaps) - which you should avoid if possible - you better also not use anything but trivial/POD types across the library boundary to save yourself some massive headaches.

Allocation control for the reasons you need between boundaries in dlls is not the only use case to control allocation. If you sink allocation inside a function without providing any interface to control that allocation, you are effectively out of control for the allocation in those functions.

**Comment by hsutter** [comment]
Hi! Quick acks:

- By the law of exclusivity I think you essentially mean the borrow checker. That's not directly supported, though the [Lifetime profile](https://wg21.link/p1179) has an experimental "SharedOwner" concept.
- Yes, you should be able to open the hood and write low-level code in Cpp2.
- Yes, caller-allocated out and callee-allocated out are known useful use cases. I think Cpp2 supports both at least as well as Cpp1.
- Pointers are still available. If with Cpp2's parameter kinds you still think you want a reference (including as parameter), you almost certainly want a pointer.
- Unsafe code is available via opt-out (I'm in the middle of adding some finer-grained opt-outs for the run-time safety checks).

**Comment by germandiagogomez** [comment]
> Unsafe code is available via opt-out (I'm in the middle of adding some finer-grained opt-outs for the run-time safety checks).

Not sure I get this. You mean by default safety and if you want unsafety then get it by asking or the opposite? Opt-out of safe to unsafe is what you mean?
