### ISSUE TITLE
[BUG] License is incompatible with contributions

### ISSUE THREAD

**Issue by Josaphat** [hsutter/cppfront#1308]
**Describe the bug**
I'm not a lawyer, but I have quite a bit of experience with licenses. It would seem to me that the CC-BY-NC-ND-4.0 license is incompatible with contributions. Specifically the `ND` (No Derivatives) portion.

In order for the contribution agreement (CLA) to go into effect, one must be making a contribution. But if one can't prepare a derivative work and distribute it, one cannot make a contribution--at least not via github because creating a github pull request requires creating a fork which includes the contribution (i.e. a derivative work).

Technically speaking, anyone who has created a PR has violated the license.

This is clearly against the intent
> [This] license does encourage contributions, and there is a CLA.
> https://github.com/hsutter/cppfront/issues/122#issuecomment-1327833311

I can't find a license that would be compatible with the intent but not open to abuse.

The best I can think of is to amend the LICENSE file with an exception for derivative works made "in good faith" for contributing to the project. (Again, not a lawyer).

**Comment by hsutter** [comment]
Indeed, the CC-BY-NC-CD-4.0 license is temporary. While the project was experimental, I wanted to exclude commercial use and exclude people using it to create incompatible/divergent forks.

My plan is to switch from that to Apache 2.0 with LLVM Exception, which does allow commercial use and derivative works. (Actually, this issue is well-timed because I was planning to do that in the next week or two.) Would that address your concern?

**Comment by hsutter** [comment]
Since this prodded me to do a task I had on my do-soon list anyway: The draft Apache license change is now #1309.

**Comment by hsutter** [comment]
Closed with #1309. Thanks!
