### ISSUE TITLE
[SUGGESTION] discard the _ type for templates

### ISSUE THREAD

**Issue by dmicsa** [hsutter/cppfront#135]
Would be nice to write a template function like in other dynamic languages. 

For example instead of:
  add(a : _, b : _ ) -> _ 
is simpler 
  add(a, b) -> _

**Comment by hsutter** [comment]
I've considered that, and the syntax deliberately leaves the door open to that because a key goal is "defaults by omitting unused parts."

As with most "simple function declaration syntax" items, a key motivator is expression-scope functions (aka lambdas in today's syntax) ... see [the talk at 1:29:45](https://youtu.be/ELeZAKCN4tY?t=5385) for a summary and examples.

So for

    :(a : _, b : _ )

I am thinking about allowing

    :(a: , b: )

or even 

    :(a,b)

though I've been holding back a bit for two reasons:

- I'm not sure saving two characters is necessarily worth it, though it could be for example if it means that some examples look less like line noise (which is important).
- I like the current stake in the ground that you can grep for `:` and find every declaration, including that a simple first-cut "Find Definition of <name>" can be implemented as a grep for `name\s+:`... we are so far away from being able to do that in today's syntax, and that's part of making C++ 10x more toolable which is one of my three goals. If we allow omitting the `:` above, then I worry it might compromise that toolability feature just to save a character.

So I'm more open to allowing omitting the `_` in the future, and more concerned about omitting the `:`.

**Comment by dmicsa** [comment]
Herb first of all thank you very much for this experiment that gives us hope for a modern C++(2)! Isn't only the colon is about all other extra operators that we can leave w/o them. I have Julia in my mind. :) 

For example:

add : (a : _, b : _ ) -> _ = {a + b}
Could be:
add(a, b) _ {a + b}
or quite: 
add(a, b){a + b}

**Comment by hsutter** [comment]
Making this an unnamed expression function (aka lambda) where the brevity really helps the most, you wrote:

> `:(a : _, b : _ ) -> _ = {a + b}`

Note that's not quite Cpp2 syntax... if I understand your intended meaning correctly, the fully explicit version of that would be:

`:(a:_, b:_) -> _ = { return a + b; }`

and Cpp2 does already let you write this as:

`:(a:_, b:_) = a + b;`

which I think that's only 5 characters away from your ideal, and preserves the universally consistent ability to grep for the definitions of all names, including ones used in the lambda body, using the `name\s+:` regex. But I understand what you want, and I'll keep the request for additional terseness in mind. Thanks!
