### ISSUE TITLE
[SUGGESTION] Move arguments to in and copy parameters

### ISSUE THREAD

**Issue by Helios-vmg** [hsutter/cppfront#156]
Example:
```
main: () -> int = {
    x: std::string = "x";
    y: std::string = "y";
    f(x);
    g(y);
}

f: (copy s: std::string) = {
    std::cout << s << std::endl;
}

g: (in s: std::string) = {
    std::cout << s << std::endl;
    h(s);
}

h: (in s: std::string) = {
    std::cout << s << std::endl;
}
```
The calls to f() and g() are the last uses of x and y in main(), and so moving them is safe, and in the case of f() it saves a copy. Note, however, that it is not possible to move s in the call to h().

**Comment by hsutter** [comment]
In general, I do intend to explore moving from last use of locals... before you can find the commented-out current limitation here: https://github.com/hsutter/cppfront/blob/main/source/sema.h#L403-L404

**Comment by hsutter** [comment]
I've now taken another stab and re-enabling it, by not moving from last use in loops, `out` arguments, and initializers... the current checkin now handles your example, Thanks!

But note I still view this (move-from-last-use of locals) as experimental because I'm pretty sure there are still cases where we don't want to implicitly move and I'll be watching to discover those.

**Comment by hsutter** [comment]
One of the interesting things is how often that new rule fires in the regression tests, see this checkin: 4a7821f272b8172cecd7bb36b5f8b6e49476dfb3

Many of those look like good (if minor) performance improvements. But I still view it as an experiment in progress.

Thanks for re-raising this.
