### ISSUE TITLE
[SUGGESTION] Step By Step Installation/Usage Instructions With Pictures

### ISSUE THREAD

**Issue by Tiptup300** [hsutter/cppfront#171]
I use linux on my old laptop to get it to work. It's my dev machine. I only sometimes get maybe 20-15 minutes to program per day so I usually don't have too much time to explore how to install these more effort-needing software. I would love to start programming in cppfront, I'm learning c++ for the first time because I really liked the presentation video.

But, I don't know how to do that though, I say I'll get to it at some point, but who knows.

I'm using debian linux, but I feel like usage would go up if it were more accessible for beginners.

**Comment by SebastianTroy** [comment]
Sorry, but this is explicitly not meant to be accessible. It is an experiment, a work in progress, a personal pet project with only a few really dedicated C++ nerds (complement) working on it. It is not feature complete and it is likely to change under your feet.
Herb has mentioned that he will open it up more if the experiment is a success, but that may be up to a few years...
Thay being said, if you are still really keen, know that all you need to do is install a C++ compiler that supports most of C++20, compile cppfront to an executable using that compiler, run this executable, passing your c++2 syntax file to it, and voila, you get out a normal C++ file out of it that you can use normally.
If those instructions are too overwhelming (I don't know how new you are to C++ or programming in general) then this project really isn't for you right now. And with only 20 minutes a day, perhaps fighting with C++ toolchains is not the best way to get into things.


On 21 December 2022 04:58:35 Matthew Deweese ***@***.***> wrote:

I use linux on my old laptop to get it to work. It's my dev machine. I only sometimes get maybe 20-15 minutes to program per day so I usually don't have too much time to explore how to install these more effort-needing software. I would love to start programming in cppfront, I'm learning c++ for the first time because I really liked the presentation video.

But, I don't know how to do that though, I say I'll get to it at some point, but who knows.

I'm using debian linux, but I feel like usage would go up if it were more accessible for beginners.

**Comment by Tiptup300** [comment]
Makes sense, I'll give it a shot thank you!

**Comment by hsutter** [comment]
@Tiptup300 Thanks for the interest, and thanks for understanding!
