### ISSUE TITLE
[BUG] Incorrect translation of direct calls to anonymous callables

### ISSUE THREAD

**Issue by jarzec** [hsutter/cppfront#179]
**Describe the bug**
`cppfront` fails to correctly translate direct calls to anonymous callables.

**To Reproduce**
1. The following code is translated incorrectly by `cppfront`:
```
// pure2-anonymous-callable.cpp2
main: () -> int = {
    std::cout << std::hash<int>()(0) << std::endl;
    return 0;
}
```
2. Command lines including which C++ compiler you are using
`cppfront` was compiled using g++-10.
The translation was performed as:
```
./cppfront pure2-anonymous-callable.cpp2
```
2. Expected result
The pertinent part of the resulting .cpp file should be:
```
[[nodiscard]] auto main() -> int{
    std::cout << std::hash<int>()(0) << std::endl;
    return 0; 
}
```
4. Actual result
Invalid C++ code:
```
[[nodiscard]] auto main() -> int{
    std::cout << std::hash<int>()    << std::endl;
    return 0; 
}
```
**Additional context**
With extra parens, as in `(std::hash<int>())(0)`,  the translation is performed correctly i.e. the statement is not altered.

**Comment by hsutter** [comment]
@filipsajdak Would you like to take this one? This is from the new UFCS code in `emit(postfix_expression_node ...)`.

Here's an even more minimal repro:

```
f: () = {
    g<int>()(0);
}
```

Which translates to:

```
auto f() -> void{
    g<int>(); // this should be g<int>()(0)
}
```

Here's what I've found:

- `args` is being overwritten, because two non-nested function calls are active at the same time without having been added to the prefix/suffix lists yet. (Possible idea: Maybe change `args` from being a `std::optional<text_chunks_with_parens_position>` to a `std::vector<text_chunks_with_parens_position>`, which can still be empty like an optional, but which can store more than one non-nested function call?)
- Also, it appears that `print_to_text_chunks` for the `(0)` expression-list is generating two chunks, an empty chunk `""` and a zero chunk `"0"`. That's probably a bug?

That's what I've found so far! Do you want to take a look?

**Comment by hsutter** [comment]
Aha, I think in describing the problem I found the answer:

> the right thing is that when about to store to args we should first see if it already holds something and if so flush it? Hmm, maybe that's simplest...

That seems to work with the new test case and regression-clean.

@filipsajdak could you please review my checkin 4d0cf5bf1410ecb5347c90c6b629565d62d29cb9 and see if it makes sense to you. Thanks!

**Comment by hsutter** [comment]
And thanks @jarzec ! Good bug.

**Comment by filipsajdak** [comment]
Looks good! I was thinking about creating a function like `flush_args`. Happy that you came up with the same idea. 

Sorry for not getting into that issue quicker - I was fighting with “as casts”.
