### ISSUE TITLE
[BUG] narrowing as() cast to optional (excidental)

### ISSUE THREAD

**Issue by filipsajdak** [hsutter/cppfront#199]
Given code:
```cpp
main: () -> int = {

    double_max := std::numeric_limits<double>::max();
    x := double_max as std::optional<int>;

    std::cout << "x = '(x)$'" << std::endl;

}
```

### Expected result

Fail to compile or empty due to lack of possibility to cast without narrowing.

### Actual

```
../tests/bug_cast_to_optional.cpp2... ok (all Cpp2, passes safety checks)

x = '2147483647'
```

### Cause

`double_max as std::optional<int>` matches below `as()` overload.
```cpp
template< typename C, typename X >
auto as( X const& x ) -> auto
    requires (!std::is_same_v<C, X> && requires { C{x}; })
{
    return C{x};
}
```

Potentially can give the same results for other types, with constructors taking one `double` argument or anything that can cast to it.

**Comment by hsutter** [comment]
Interesting... I hadn't thought about `as` casts **_to_** the dynamic library types, because you can typically just converting-construct or assign or emplace values into them.

But I think I've thought of a way to do this, in the commit above. It works for this test case and a few others. Please take a look and let me know if I missed anything.
