### ISSUE TITLE
[BUG] variable used in string interpolation not treated as last use of variable

### ISSUE THREAD

**Issue by filipsajdak** [hsutter/cppfront#216]
In the current implementation, cppfront adds a move to the last use of a variable. Unfortunately, it does not take into account variables used in string interpolation. That makes the code below:
```cpp
by_value: (copy x : std::string) = {
}

main: () -> int = {
    s: std::string = "Hello World!";
    by_value(s);
    std::cout << "s = '(s)$'" << std::endl;
}
```
Generates (skipping boilerplate):
```cpp
auto by_value(std::string x) -> void{
}

[[nodiscard]] auto main() -> int{
    std::string s {"Hello World!"}; 
    by_value(std::move(s));
    std::cout << "s = '" + cpp2::to_string(s) + "'" << std::endl;
}
```
and produce:
```
s = ''
```
Instead of:
```
s = 'Hello World!'
```

**Comment by hsutter** [comment]
Thanks! This is now fixed with commit a0c8f1d04b0e4f1c63223553b7397713d6ea3d63.

Moving string interpolation from late (lowering) to early (lexing) was on my to-do list. This commit moves it to lexing, and this way the contents of captured/interpolated expressions tokenize normally, and then everything else downstream just lights up automatically from that change (move from last use, UFCS, operator rewriting, ...).

**Comment by filipsajdak** [comment]
You probably mean: https://github.com/hsutter/cppfront/commit/203859198f82908c760a481a5fbe10755aa6bc09

Thank you for a fast fix. I hope it did not ruin your to-do list priorities.

**Comment by hsutter** [comment]
No, it was already on my list, and bug fixes are helpful anytime, thanks!
