### ISSUE TITLE
[SUGGESTION] clarify need for move/forward

### ISSUE THREAD

**Issue by maddanio** [hsutter/cppfront#221]
Can someone clarify why move and forward are needed? Seems to me in/out are statements of intent while move/forward are implementation details? Recently saw a talk about the val language and it seems they get a lot of mileage out of just in/inout/out.

**Comment by SebastianTroy** [comment]
It is my understanding that move is a statement of movement of ownership, an important intent to clarify in a language that places the responsibility of memory aloocation and deallocation on the user.
The implementation detail thereafter does lead to a slew or optimisation opportunities, but they are a bonus, not the requirement afaik.

My expertise on forward is lacking, I am also interested to know if it is merely implementation detail or also conveys some intent


On 12 January 2023 08:42:48 Daniel Oberhoff ***@***.***> wrote:

Can someone clarify why move and forward are needed? Seems to me in/out are statements of intent while move/forward are implementation details? Recently saw a talk about the val language and it seems they get a lot of mileage out of just in/inout/out.

**Comment by hsutter** [comment]
> Seems to me in/out are statements of intent while move/forward are implementation details?

> So if "in" and "move" are collapsed to just "in", then I guess "forward" becomes obsolete too?

I attempt to answer this in [paper d0708](https://github.com/hsutter/708/blob/main/708.pdf), particularly the summary table in section 1.1.2. See also the other resources in [README.md > 2020: Parameter passing](https://github.com/hsutter/cppfront#2020-parameter-passing).

The short answer is that writing `in` vs. `move` isn't leaking implementation detail, it's expressing the intent of the callee which affects what the caller can expect:
- An `in` parameter says that the callee will read but not modify the object (it is `const` inside the callee), and the caller can pass any initialized object. 
- A `move` parameter says that the callee will consume the value of the argument by moving it out, and the caller can pass any rvalue (but not an an lvalue, a named object where this is not its definite last use). That's important because if the caller is trying to pass a named variable (which means they could try to use the name again on the very next line), the caller needs to know they shouldn't try to use the object's value again before first resetting it to a new value... and because a `move` parameter accepts only an rvalue, the caller who tries to pass an lvalue will fail and has to explicitly write `move` to say 'trust me, treat this as an rvalue' to make it clear they know what they're getting into.

And `forward` is very special -- it's for wrapper functions, and specially tracks the argument's const-ness (const or non-const) and value category (lvalue vs rvalue) so that when the callee then uses the parameter those properties are passed along, including that the callee body that passes the parameter to some other function will do different overload resolution depending on whether the argument is const or not and/or an lvalue or not.

> "forward" is only used in templates, 

That's effectively true in Cpp1, and templates are an implementation detail in Cpp2. But one of the things Cpp2 generalizes is that you can `forward` a concrete type (that is not template parameter type). This is implemented, and there's a live demo in [this 1-min clip of the CppCon 2022 talk](https://youtube.com/clip/UgkxNEcpLR5i3rKFf0DFOe0aInWYetHyi1Ay) that shows how it works.

**Comment by jcanizales** [comment]
Thank you for the summary!

**Comment by maddanio** [comment]
Yes Thanks a lot!

**Comment by AbhinavK00** [comment]
Val also has move parameters, they call it "sink". Just saying

**Comment by maddanio** [comment]
ah, right, yah, sorry, guess I should have read more before asking...sorry again
