### ISSUE TITLE
[SUGGESTION] down with goto / ES.76's exception

### ISSUE THREAD

**Issue by DaemonSnake** [hsutter/cppfront#228]
According to ES.76, `goto` should be avoided except to break out of nested loops.
If we want to get rid of `goto` we need an alternative for that exception.

**Will your feature suggestion eliminate X% of security vulnerabilities of a given kind in current C++ code?**
Vulnerabilities like Apple's 'goto fail' comes to mind

**Will your feature suggestion _automate or eliminate_ X% of current C++ guidance literature?** 
The goal is to eliminate ES.76

**Describe alternatives you've considered.**
- Go and Rust have come to a similar solution, labeled break.
```go
outer:
   for {
     for {
        if cond {
           break outer
        }
     }
   }
```
```rust
   'outer: loop {
      loop {
         break 'outer;
      }
   }
```
- Php's numbered breaks (`break 2` for instance). This has the disadvantage of potentially causing possible counting confusion (starting at 0 or 1)
- Just get rid of goto without an alternative for this use case
For this solution to work it will force one of the following patterns to be used:

  - move loops in lambdas / functions and use 'return' as a break
  - add mutable variable and conditions inside different levels of the loop

**Comment by JohelEGP** [comment]
Some alternatives proposed for C++: https://wg21.link/P0082, https://wg21.link/P2635. IIRC, there's more.

**Comment by hsutter** [comment]
Thanks for the suggestion, and for following the suggestion template!

I think there are several related issues here. Let me try to tease some apart...

### Named `break` and `continue` to refer to outer loops

Yes, these can be useful in nested loops, and I'm considering them in Cpp2. But I view their main benefit as being able to get rid of extra "flag" variable state that exists only to `break`/`continue` multiple loops, not particularly as being able to get rid of `goto`s. so let's talk about `goto`...

### Forward-and-out `goto`

Structured programming is Good. `goto` gets its well-deserved bad reputation because it can create _unstructured_ control flow, including _unstructured_ loops or even jumping inside arbitrary loops or other control flow. These are the specific things [Dijkstra called out in his CACM letter](https://homepages.cwi.nl/~storm/teaching/reader/Dijkstra68.pdf) where he pointed out that `if` and `while` and function calls are structured and easy to reason about, and "bad" unstructured `goto` isn't easy to reason about (because then the human has to think about dynamic structure, not static structure, which is way harder). Because all `goto` at that time allowed those unstructured uses, Dijkstra rightly concluded that
> "The `go to` statement **_as it stands today_** is just too primitive." [emphasis added]

Key observation (and I'm not the first to say this): Those unstructured misuses of `goto` involve jumping backward and/or into scopes (some of which is already banned in C++).

A `goto` that can only jump forward, and to later in the same scope or enclosing scope, can never introduce unstructured control flow and does not have these problems. And such a `goto` is actually useful for exactly this (C-style but useful) `goto fail;` / `goto END;` use case which can lead to simpler program logic and avoid extra variables and code duplication. So my view is that forward-and-out `goto` is not inherently bad, and can actually lead to better code... and I realize saying that out loud might provoke a pitchforks-and-lederhosen response! :)

And if any of you are thinking, "how could Herb say something nice about `goto`?! I would never use `goto`," consider that you already do use it and you already hunger for more of it... because **forward-goto is exactly what `switch` and `inspect`/`match` do,** and Dijkstra (and Wirth and Hoare) was well aware of it and explicitly mentioned it at the end of his CACM letter. Note these two short paragraphs list forward-`goto` as useful for:
- "alarm exits," like `goto fail;`, which is structured;
- "case construction," like `switch` and `inspect`, which is structured; and
- avoiding contorting your code, noting that rewriting the code just to avoid a forward-`goto` can be actually undesirable and make the code harder to maintain.

![image](https://user-images.githubusercontent.com/1801526/212562039-0cd2027c-cce6-4d7a-97fb-ef56ae7e5958.png)

If I do allow forwad-and-out `goto label;`, I would not want to introduce the new one-off concept of labels into Cpp2, but slightly extend the existing way we have to generate names, which is to allow an empty `:` declaration... like all declarations it really does declare a name, but that's all ti does:

```
test: () = {
    ...
    if something {
        goto end;  // potential extension: forward-only goto
    }
    ...
    end: /*comefrom*/ ;  // potential extension: empty declaration
        // possibly with some "comefrom" tag to make the intent explicitly clear
    ... cleanup logic ...
}
```

"But wait!" you may rightly ask with some alarm, "wasn't that exactly the `goto fail;` vulnerability?" I don't think so, hear me out...

### The `goto fail;` vulnerability

The code was basically this:

```
if ((err = SSLHashSHA1.update(&hashCtx, &signedParams)) != 0)
    goto fail;  // conditional
    goto fail;  // unconditional
```

The problem is that in C and C++ only the first `goto fail;` is part of the `if /*true*/` branch. The second `goto fail;` always happens. The visual indentation doesn't matter, it's the same as if written more visibly like this:

```
if ((err = SSLHashSHA1.update(&hashCtx, &signedParams)) != 0)
    goto fail;  // conditional
goto fail;  // unconditional
```

I view this particular bug as already solved in Cpp2 because Cpp2 requires `{` `}` around branch bodies, which makes the bug visible even if you still mis-indent the second one:

```
if (err = SSLHashSHA1.update(hashCtx&, signedParams&)) != 0 {
    goto fail;  // conditional (if I allow forward-and-out goto as an extension)
    }
    goto fail;  // unconditional - now pretty visible
```

So I think the problem with `goto fail;` wasn't the `goto fail;` itself... after all, the first one of those was fine. The problem was the unscoped branch body which misled the programmer about the second `goto`, and this is not possible in Cpp2... this class of bug is exactly one of the reasons why Cpp2 requires those `{` `}` (another is that a Cpp1 macro used inside a Cpp2 branch body has the usual evil of macros including that it could expand into multiple statements which can create this same bug in an even less visible way).

Does that capture most of the issues? Additional examples and arguments (both pro and contrarian) welcome!

**Comment by switch-blade-stuff** [comment]
I personally am not a fan of the `label:;` syntax, it looks a bit noisy and ambiguous with variable declaration. I would rather have `id-expression ':'` stand in for type deduction rather than labels.

It could be that labels are applied to a scope (maybe without the colon even), something like
```
...
goto handle_err;
...

handle_err {
    ...
}
```

But, this would also introduce potential ambiguity with the proposals to use `{}` for lists and `std::format`-style formatting, and any other future proposals where braces are involved.

**Comment by DaemonSnake** [comment]
> Does that capture most of the issues? Additional examples and arguments (both pro and contrarian) welcome!

Thanks for this very detailed and comprehensive response.
It does capture the issues well.
Both forward-only goto and named break/continue would allow discarding ES.76.

> And if any of you are thinking, "how could Herb say something nice about `goto`?! I would never use `goto`," consider that you already do use it and you already hunger for more of it... because **forward-goto is exactly what `switch` and `inspect`/`match` do,** and Dijkstra was well aware of it and explicitly mentioned it at the end of his CACM letter citing also Wirth and Hoare. Note these two short paragraphs list forward-`goto` as useful for:
> 
> * "alarm exits," like `goto fail;`, which is structured;
> * "case construction," like `switch` and `inspect`, which is structured; and
> * avoiding contorting your code, noting that rewriting the code just to avoid a forward-`goto` can be actually undesirable and make the code harder to maintain.

On that front, I see the argument against explicit `goto` being that it solves too many use cases at once causing the detection of which case is being solved not self-apparent, particularly if those are combined, worse yet if the function is too large/deep.

For the "alarm exits" like `goto fail` we can solve this issue with lambdas and with minimal amount of refactoring:
```
test: () = {
    ...
    cleanup:= :() = {
        ... cleanup logic ...
    };
    if something {
        cleanup();
        return;
    }
    ...
}
```
but it has been further reduced as a need with RAII patterns or "declarative control flow" like Dlang's `scope(exit)`, golang's `defer` or C++ Library Fundamentals v3's `scope_exit<>`.

For "case construction", using switch or inspect makes goto a complete downgrade in terms of readability.

And so the last use-case I see where we have no alternative is nested loops continue/break.
If we have named break/continue I'm not sure goto will still be that useful.

**Comment by switch-blade-stuff** [comment]
Thing is though, by that point a named continue is essentially a goto but with a different name.

And it could also lead to this horrific thing (in pseudocode)
```
do
{
    continue some_label;

some_label:
    // ...
} while (false);
```

which is no different from

```
goto some_label;

some_label:
// ...
```

Yes, `goto` does not have much of a use with modern language constructs like RAII, yet it is still a useful feature in some cases. You may not always want to restructure your logic in a way to suit RAII wrappers, or may not want to deal with said RAII boilerplate or exceptions, or a myriad of boolean flags.

Instead in my opinion it is better to either still allow some amount of `goto` in safe code with lifetime and other restrictions, or to make it an opt-in and keep it restricted as an "unsafe" feature.

I also personally am not a big fan of removing something (that doesnt cost us much to keep) just because it is "not a jack-of-all-trades solution".

**Comment by DaemonSnake** [comment]
> And it could also lead to this horrific thing (in pseudocode)
> 
> ```
> do
> {
>     continue some_label;
> 
> some_label:
>     // ...
> } while (false);
> ```
The example you provide is just a goto and not what a named break/continue would entail.
it would be instead something like:
```c++
some_name : do {
   ...
   continue some_name
   ...
} while (false);
```
So we agree 'goto'
> could also lead to this horrific thing

As the core guideline stipulates:
> ES.76: Avoid goto
> Reason Readability, avoidance of errors.
> There are better control structures for humans; goto is for machine-generated code.
> Exception Breaking out of a nested loop. In that case, always jump forwards.

**Comment by hsutter** [comment]
I've been meaning to implement `break` and `continue` anyway, including for named targets... and per this thread it occurred to me it could be implemented pretty easily with forward-`goto`.

Here's the quick-and-dirty Godbolt mockup showing the idea: https://godbolt.org/z/j4cGh7KGs

Here's the commit that adds it to cppfront: 860992221bd613e4b72a3cd3b496e0b6b70611d8 (and minor tidying in 1076a7a39d272008cbbc8e5598a595bc2e20c4b9)

Here is the test case: https://github.com/hsutter/cppfront/blob/main/regression-tests/pure2-break-continue.cpp2

And an example from that test case:

    i := 0;
    outer: while i<3 next i++ {  // loop named "outer"
        j := 0;
        inner: while j<3 next j++ {  // loop named "inner"
            std::cout << i << j << " ";
            if j == 1 {
                continue outer;  // continue the outer loop
            }
            std::cout << "inner ";
        }
        std::cout << "outer ";
    }

**Comment by hsutter** [comment]
Of the compelling use cases for `goto` that I know of, that leaves only the `goto END;` style, and I agree scope guards (such as GSL `final_action`) can be a good solution there. I'll give further thought to whether they need language support...

But anyway, please take a look at this implementation of named loops with named `break`/`continue`... I'd appreciate another set of eyes to see if I wrote any bugs, and that the usability satisfies your use cases.

**Comment by jcanizales** [comment]
I appreciate the reasoned exposition about when `goto`s might not be that bad. It is a way of saying "I disagree with guideline ES.76", which is fine because this is your personal project :slightly_smiling_face: But I just wanted to point out that it deviates from the "rules of the game" you set for yourself.

"Goto but the compiler only lets you put the label forward and out" itches me for a second reason: While compiler enforcing is strictly better than an English-language rule in a guideline, just enforcing those guidelines does not simplify the language. We'd still have to teach those things.

So as a fan of the project, I'm glad that you implemented the named breaks and continues :slightly_smiling_face: . IMO vast simpler, and in my experience (which agrees with ES.76) enough to get rid of goto.

**Comment by hsutter** [comment]
@jcanizales I think we're in strong agreement, and I don't think I was disagreeing with ES.76 per se, which lists breaking out of nested loops as an exception, with the guidance "always jump forwards." Totally agree.

But the holy grail is always "enable the programmer to directly express their intent," such as by a `switch`/`inspect` or now here with a labeled `break`/`continue`. Now that I've added the latter, it removes most of the remaining benefit of adding a safe `goto` (which I still haven't implemented and may never, and removes the need to teach the Exception in ES.76).

The only main use case I know of that remains is the `goto exit` idiom, and now I remember that Cpp2 already has `cpp2util.h`'s `finally_success` so that should already be covered too.
