### ISSUE TITLE
[QUESTION] How to make of `inout` parameters of type `const T`?

### ISSUE THREAD

**Issue by leejy12** [hsutter/cppfront#250]
I was thinking of how Cpp2 would implement [std::min](https://en.cppreference.com/w/cpp/algorithm/min#Version_1). Its signature looks like this:
```cpp
template <typename T>
const T& min(const T& a, const T& b);
```

I came up with this answer (the template syntax is copied from https://github.com/hsutter/cppfront/issues/248#issuecomment-1419217762:
```
min: <T: type> (inout a: const T, inout b: const T) -> forward const T = {
    if a < b {
        return a;
    }
    else {
        return b;
    }
}
```
https://godbolt.org/z/8Wa315arP

However, this raises some questions about `inout` and `const` parameters.

`inout x: X` means "present me an X I can read and write" and the function must contain a non-const use of X. But functions like `std::min` can't have write operations to its parameters because they're const reference. So cppfront should not give error diagnostics when there's no write operations to parameters that are `inout` and `const`.

I think this slight conflict of intentions could be confusing to beginners learning the language. Unless there's a better way, we could treat this as a special case of using `inout` and `const` for functions that MUST take parameters by const reference. I don't think there's many functions that do, I can only think of `std::min`, `std::max`, and `std::clamp`.

**Comment by SebastianTroy** [comment]
Would the Cpp2 way be use in parameters, and make them pointers, then return a pointer?

min: <T: type> (in a: T*, in b: T*) -> T* = {
    if *a < *b {
        return a;
    }
    else {
        return b;
    }
}

(I'm pretty sure my pointer syntax here is wrong...)

On 7 February 2023 09:52:12 Junyoung Lee ***@***.***> wrote:

I was thinking of how Cpp2 would implement std::min<https://en.cppreference.com/w/cpp/algorithm/min#Version_1>. Its signature looks like this:

template <typename T>
const T& min(const T& a, const T& b);

I came up with this answer (the template syntax is copied from #248 (comment)<https://github.com/hsutter/cppfront/issues/248#issuecomment-1419217762>:

min: <T: type> (inout a: const T, inout b: const T) -> forward const T = {
    if a < b {
        return a;
    }
    else {
        return b;
    }
}


https://godbolt.org/z/8Wa315arP

However, this raises some questions about inout and const parameters.

inout x: X means "present me an X I can read and write" and the function must contain a non-const use of X. But functions like std::min can't have write operations to its parameters because they're const reference. So cppfront should not give error diagnostics when there's no write operations to parameters that are inout and const.

I think this slight conflict of intentions could be confusing to beginners learning the language. Unless there's a better way, we could treat this as a special case of using inout and const for functions that MUST take parameters by const reference. I don't think there's many functions that do, I can only think of std::min, std::max, and std::clamp.

**Comment by AbhinavK00** [comment]
Taking in by a pointer in this case looks like a work-around, we probably need a new way for this use case. 

Off topic but I think template syntax could just have 
`func : <T , U> ()=` instead of `func : <T : type, U : type>` so that template arguments can default to typename and the function writer can specify otherwise.

**Comment by filipsajdak** [comment]
@leejy12, what you try to do is probably:

```cpp
min: (in a, in b) -> forward _ = {
    if a < b {
        return a;
    }
    else {
        return b;
    }
}
```
That will generate the following code:
```cpp
[[nodiscard]] auto min(auto const& a, auto const& b) -> decltype(auto){
    if (cpp2::cmp_less(a,b)) {
        return a; 
    }
    else {
        return b; 
    }
}
```

The general rule of cppfront that I have learned is to think about my intentions rather than what I expect generated code to look like. 

In this example, if I want to read only from the variable, then it means I should use the `in` passing style. When you use `inout` passing style and don't write to the variable, cppfront will generate an error diagnostic to use `in` instead - check https://github.com/hsutter/708/blob/main/708.pdf (chapter 1.3.2 `Inout parameters`).

Please note that `in` passing style is the default so that you can write the min function as:
```cpp
min: (a, b) -> forward _ = {
    if a < b {
        return a;
    }
    else {
        return b;
    }
}
```

**Comment by jcanizales** [comment]
@leejy12 as you said:

> `inout x: X` means "present me an X I can read and write" 

`const` means "you can't write to it". So you cannot use `inout` with it. Simple as that.

"The function must contain a non-const use of X" is just the compiler being helpful and ensuring you're not making a mistake. Because you want it to be `const`, it can't be `inout`. It must be `in`, as @filipsajdak shows.

**Comment by leejy12** [comment]
Ah, I forgot about generic `_` parameters. Thanks for your answers @filipsajdak @jcanizales !

**Comment by hsutter** [comment]
Yes, thanks to @leejy12 for raising the question...

and to @filipsajdak who wrote this...
> The general rule of cppfront that I have learned is to think about my intentions rather than what I expect generated code to look like.

and to @jcanizales who wrote this...
> `const` means "you can't write to it". So you cannot use `inout` with it. Simple as that.

... which made me realize that `const` qualification doesn't make sense for parameters (except `copy` parameters, because only those are expressing the intent of really making a new variable... all the others are conceptually, and usually actually, aliases for the original argument).

So I should just disallow `const` for non-copy parameters... done, commit coming up...

Thanks again!

**Comment by JohelEGP** [comment]
> @leejy12, what you try to do is probably:
> 
> ```c++
> min: (in a, in b) -> forward _ = {
>     if a < b {
>         return a;
>     }
>     else {
>         return b;
>     }
> }
> ```
> 
> That will generate the following code:
> 
> ```c++
> [[nodiscard]] auto min(auto const& a, auto const& b) -> decltype(auto){
>     if (cpp2::cmp_less(a,b)) {
>         return a; 
>     }
>     else {
>         return b; 
>     }
> }
> ```
> -- Extract from https://github.com/hsutter/cppfront/issues/250#issuecomment-1421434308

That no longer works: <https://godbolt.org/z/fh45f1ecT>.
```output
main.cpp2(3,9): error: a 'forward' return type cannot return an 'in' or 'move' parameter
main.cpp2(6,9): error: a 'forward' return type cannot return an 'in' or 'move' parameter
```

**Comment by JohelEGP** [comment]
Here's why: <https://github.com/hsutter/cppfront/issues/248#issuecomment-1493054740>.
Feels like the usual entanglement of lifetime and something else (Was it value category? The shape of the parameter?).
An attempt to provide safety that removes legit use-cases.

**Comment by JohelEGP** [comment]
I feel like I remember now.
It feels like when a type author has a function that takes an reference to `const`:
```C++
struct t {
  void f(const std::string&);
};
```
And in an attempt to be useful, they overload it with:
```C++
struct t {
  void f(const std::string&);
  void f(std::string&&) = delete; // No, unsafe! Use the other overload.
};
```
But that's conflating lifetime and value category.
And it has unintended consequences or removes legit use-cases
(e.g. `t().f("")`, where the caller knows its safe).

**Comment by JohelEGP** [comment]
See <https://quuxplusone.github.io/blog/2019/03/11/value-category-is-not-lifetime/>.

**Comment by AbhinavK00** [comment]
> I could suggest to revert the prohibition of forward returning an in parameter.

I argued for this some time back and still think it should be done.
I think the best way to view `in` parameters is to see them  as `const&` which are sometimes optimised to copies if certain conditions are met. I don't think a new convention is needed (6 are already too much).

**Comment by JohelEGP** [comment]
I agree with that starting at <https://github.com/hsutter/cppfront/issues/250#issuecomment-1556444804>.
But not as a way to implement `std::min` because
> That relies on an implementation detail (the optimization done by for in parameters).
> -- <https://github.com/hsutter/cppfront/issues/250#issuecomment-1557559385>

**Comment by JohelEGP** [comment]
This works, for now: <https://cpp2.godbolt.org/z/rnKoEcaae>.
```Cpp2
min: <T> (a: T, b: T) -> std::type_identity_t<decltype((a))> = {
    if a < b {
        return a;
    }
    else {
        return b;
    }
}
```
Not for concrete `min`.
And someday even this example could be optimized like the concrete parameter `(in x: int)`.

**Comment by JohelEGP** [comment]
> > `const` means "you can't write to it". So you cannot use `inout` with it. Simple as that.
> 
> ... which made me realize that `const` qualification doesn't make sense for parameters (except `copy` parameters, because only those are expressing the intent of really making a new variable... all the others are conceptually, and usually actually, aliases for the original argument).

`in` parameters are optimized, and the difference is observable (#686).
How about allowing `inout _: const _` parameters to mean an `in` parameter with an address?
That way, we can implement `std::min` (concrete or generic) in Cpp2.

**Comment by AbhinavK00** [comment]
But don't you think that is is the kind of exceptions that cpp2 is trying to solve.

**Comment by JohelEGP** [comment]
This made my think about parameter aliasing.

One way to look at the suggestion of allowing `inout _: const _` parameters
is that `out` and `inout` allow modifying passed arguments, and thus alias.
By adding `const` to `inout`, we remove the modification aspect, but retain aliasing.

Another thought of mine is making all `in` parameters not alias if that was possible.
And to require the `inout _: const _` spelling for otherwise aliasing `in` parameters.
Perhaps that way we can get a better default and more performance,
like Rust parameters as I once understood them (I think it was after watching a talk by David Sankel).

**Comment by AbhinavK00** [comment]
Rust parameters are faster because they're passed with `restrict`.
The model that cpp2 uses is superior in many ways, (hylo uses kinda close model).
1) If these kinda hacks are required, may as well fall back to references.
2) How about using pointers to indicate aliasing so we get performance AND safety by default when using the passing conventions?
I'm not sure I fully understand, but that was from what I understood.
