### ISSUE TITLE
[BUG] pointer in class can be set to `nullptr` in constructor but cannot be initialised inline

### ISSUE THREAD

**Issue by filipsajdak** [hsutter/cppfront#280]
The current implementation of cppfront (https://github.com/hsutter/cppfront/commit/4c52d2d9c6c4b7ae19ee2eeb584a5a775ba78af3) for the following code:
```cpp
node: type = {
    parent: *node;
    operator=: (out this) = {
        parent = nullptr;
    }
}
```
Generates (skipping boilerplate):
```cpp
class node  {
    private: node* parent; 
    public: node()
        : parent{ nullptr }
#line 4 "nullptr_parent_node.cpp2"
{
    }
};
```
When I tried to initialize `parent` in place:
```cpp
node: type = {
    parent: *node = nullptr;
    operator=: (out this) = {
    }
}
```
I got an error:
```
nullptr_parent_node.cpp2...
nullptr_parent_node.cpp2(2,21): error: pointer cannot be initialized to null or int - leave it uninitialized and then set it to a non-null value when you have one (at 'nullptr')
nullptr_parent_node.cpp2: error: null initialization detected
  ==> program violates lifetime safety guarantee - see previous errors
```

### Expectations

I expect to have consistent behavior here. Both ways should end up with the same results.

### Question

How will we model structures that use `nullptr`s as terminators? In the given scenario, `parent` is a non-owning pointer that can be null.

**Comment by filipsajdak** [comment]
Does https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r3-a-raw-pointer-a-t-is-non-owning applies to cppfront?

**Comment by filipsajdak** [comment]
Or more likely: https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#f42-return-a-t-to-indicate-a-position-only

**Comment by hsutter** [comment]
In Cpp2, raw pointers are expected to be non-owning pointers to a single object.

The disallowing of nulls is its own experiment, and the checks for that are known to be partial and mainly just enough to start getting a feel for what that path is like. I don't know yet whether disallowing nulls is going to work out or not, particularly since nulls will still come from Cpp1 types and functions, so I think what's there is probably roughed-in enough for now (even if it's a bit inconsistent about what it does and doesn't diagnose, as above). If as we get further along we like this path, then we can do a more complete job of disallowing nulls.

**Comment by AbhinavK00** [comment]
I think Herb can take a look at null handling in kotlin as it tackles a similar problem to cpp2. Kotlin interops with Java and therefore has null pointers coming from Java. Null pointers are not allowed by default in kotlin but there are various operators to enable and handle null pointers.
[A link to documentation ](https://kotlinlang.org/docs/null-safety.html)

**Comment by filipsajdak** [comment]
@AbhinavK00 regarding the use of `?` We have some discussion here: https://github.com/hsutter/cppfront/pull/106#issuecomment-1304303047

We end up not introducing it but the use case was different.

**Comment by AbhinavK00** [comment]
I think it was discussed in context of returning errors (from casts).
This is a different use case like you pointed out, so a discussion is worth it I guess.

Also, regarding error handling, Herb gave a cppcon talk in 2018/2019(?, don't remember clearly) but I'm curious if that's how Herb plans to implement error handling in cpp2 because it's not mentioned in road map.
(I gotta rewatch the talk because I can't remember it, but it was lightweight exceptions ig)

**Comment by JohelEGP** [comment]
It's on the first sentence of the README.
> This compiler is a work in progress and currently hilariously incomplete... basic functions work, classes will be next, then metaclasses and lightweight exceptions.
