### ISSUE TITLE
[BUG] Defining lambda that takes argument using forward passing style and calling it on function variable makes cppfront treat the variable as forwarded

### ISSUE THREAD

**Issue by filipsajdak** [hsutter/cppfront#295]
In the current implementation of cppfront (fbf55ad9efcded58f550f05ede37b5b48399a7fd), the following code:

```cpp
f_inout: (inout x) -> _ = {
    x *= 2;
    return x;
}

main: () -> int = {
    x := 21;

    l1 := :(forward x) = {
        std::cout << f_inout(forward x) << std::endl;
    };

    l1(x);

    x++;
}
```
Generates:
```cpp
[[nodiscard]] auto f_inout(auto& x) -> auto{
    x *= 2;
    return x; 
}

[[nodiscard]] auto main() -> int{
    auto x {21}; 

    auto l1 {[](auto&& x) -> void{
        std::cout << f_inout(        CPP2_FORWARD(x)) << std::endl;
    }}; 

    std::move(l1)(x);

    ++CPP2_FORWARD(x);
}
```

And will fail to compile with the error:
```
../tests/bug_lambda_forward_iife.cpp2... ok (all Cpp2, passes safety checks)

../tests/bug_lambda_forward_iife.cpp2:15:5: error: expression is not assignable
    ++CPP2_FORWARD(x);
    ^ ~~~~~~~~~~~~~~~
1 error generated.
```

The variable x was passed to the lambda defined in the `main` function and is treated as forwarded, which is not in the scope of the `main` function.

If you replace `x++` with another call to the same lambda, it will generate the following:
```cpp
[[nodiscard]] auto f_inout(auto& x) -> auto{
    x *= 2;
    return x; 
}

[[nodiscard]] auto main() -> int{
    auto x {21}; 

    auto l1 {[](auto&& x) -> void{
        std::cout << f_inout(        CPP2_FORWARD(x)) << std::endl;
    }}; 

    l1(x);

    std::move(l1)(CPP2_FORWARD(x));
}
```
And will fail to compile with the error:
```
../tests/bug_lambda_forward_iife.cpp2... ok (all Cpp2, passes safety checks)

../tests/bug_lambda_forward_iife.cpp2:10:22: error: no matching function for call to 'f_inout'
        std::cout << f_inout(        CPP2_FORWARD(x)) << std::endl;
                     ^~~~~~~
../tests/bug_lambda_forward_iife.cpp2:15:18: note: in instantiation of function template specialization 'main()::(anonymous class)::operator()<int>' requested here
    std::move(l1)(CPP2_FORWARD(x));
                 ^
../tests/bug_lambda_forward_iife.cpp2:1:20: note: candidate function [with x:auto = int] not viable: expects an lvalue for 1st argument
[[nodiscard]] auto f_inout(auto& x) -> auto{
                   ^
1 error generated.
```

If you move the definition of lambda outside of `main`, it will work as expected and will generate the following code:
```cpp
[[nodiscard]] auto f_inout(auto& x) -> auto{
    x *= 2;
    return x; 
}

auto l1 {[](auto&& x) -> void{
    std::cout << f_inout(        CPP2_FORWARD(x)) << std::endl;
}}; 

[[nodiscard]] auto main() -> int{
    auto x {21}; 

    l1(x);

    ++x;
}
```

**Comment by AbhinavK00** [comment]
One query, shouldn't the first code be
```
f_inout: (inout x) -> _ = {
    x *= 2;
    return x;
}

main: () -> int = {
    x := 21;

    l1 := :(forward x) = {
        std::cout << f_inout(inout x) << std::endl;
    };

    l1(x);

    x++;
}
```

With the argument passing convention being `inout` when forwarding argument to `f_inout` instead of `forward`?

**Comment by filipsajdak** [comment]
@AbhinavK00 on the main branch there is no `inout` on the caller side.

The example is just to show that due to this bug forwarded-type changes.

**Comment by AbhinavK00** [comment]
Sorry but I still don't understand. I believe there's a difference how we see it, it'll come in the following proposal.
With this feature being on verge on getting merged, I think I'll start the talk about syntax here. I know Herb says not to worry about syntax but I think once features make it into the language, its hard to bring changes in them.

**So here it is**
`in` arguments: No need to mark them. As `in` is the default convention on the callee side, it would be the default on the caller side too.

`out` and `inout` parameters: These two could be unified because the caller does not care as much about the initialization of the value as much as the callee (it's the callee who has to worry about reading the value). An `out` function can also accept an `inout` argument, so both can use the same syntax like this:
```cpp

func_call(arg1@, arg2@);
```
We put a suffix symbol after the argument name to symbolise "modification". It could be any symbol, I just used `@` here. I will also put my preference down below.

`move` arguments: Like `out` and `inout`, we again use a symbol but a different one because moving is fundamentally different from modification. Here's an example with two options:
```cpp

move_func_call(arg1!@);
move_func_call(arg1@@);
```
You may notice that both of the above options have the user using two symbols, it's because moving should be more "visible" than modification as it is an operation to be careful about.
As with the two options, one with `!` preceding the symbol used for showing modification or the one with two of those symbols, any could be chosen but I prefer the first one (can't really explain but I think the user is less likely to make mistakes with that one).
Now this convention could be used anywhere where we use `std::move` today if it is implemented.

`forward` arguments: This one is special. For `forward`, the caller does not worry about whether the effect on his passed value is through a wrapped function or not, so it'll NOT have it's own convention. Think about it, the standard library may have many functions which just wrap other functions which the users don't know today (because they don't need to) so why should they be supposed to know it now? As a caller, I'm only worried about expressing my intention about what effect happens on my arguments and not about function implementation so there's no need of `forward` argument passing syntax.
```cpp

foward_func_call_out(arg@);
forward_func_call_out(arg@);
forward_func_call_move(arg!@);
//no worries about implementation, we just express our intent
```
`copy` arguments: Not a fan of this one, I think this should not even exist but still I think the best way would be like this:
```cpp

func(arg.copy());
```
We just copy our object and pass it along.

**Reason**
The simple reason is that, function calls exist in largely greater amount than function definitions, you define a function once but use it indefinitely. So, the syntax for function calls should be more terse and possibly as short as possible.

**Symbols considered for using**
It's not really important which symbol we choose but I think `&` looks good.
But wait, what about the `adress of` operator?
That could be changed to a function named `addr` so we would write
```cpp

b := obj.addr(); //similar to ssize, huh
c := addr(obj); //less elegant
```
While both ways would be legal, the first way (present thanks to UFCS) is more similar to how we write it today but with some more keystrokes.

With that, the syntax would look like this:
```cpp

func_in(arg);
func_out(arg&);
func_inout(arg&);
func_move_1(arg!&); // or 
func_move_2(arg&&);
func_copy(arg.copy());
//nothing special for forward
//BONUS
v := a!&; // similar to cpp's auto v = std::move(a);
//anymore you could think of
```
With `&`, the syntax is similar to how we pass references today but since there are no references in cpp2, we could say that we just took that syntax.
I'm not concerned about symbol but Herb rightly pointed out in [this article](https://github.com/hsutter/cppfront/wiki/Design-note%3A-Postfix-unary-operators-vs-binary-operators) that we only get so many symbols to use and therefore should be careful with deciding to use the newer ones.
_BTW, I do support using `^` for pointers, can I open an issue suggesting how we could go about it? pls tell_

**Comment by filipsajdak** [comment]
The issue is still observable on current main branch (827ed79d71a8b39f35894019b4dde695a2d83ef5)

**Comment by basic-bro** [comment]
I suggest that this bug is due to the shadowing that occurs in the lambda `l1`. (It takes a parameter named `x`, which shadows the `x` from `main`'s scope. We can see this in the sema `debug_print`, which lists the following for `main`:

0 | function main
  1 |   scope
  2 |     var x
  2 |     /var 
  2 |     var l1
  2 |     var x
  2 |     scope
  3 |       *** use of x
  3 |       /scope
  2 |     /var 
  2 |     *** (18,5) DEFINITE LAST POTENTIALLY MOVING USE OF *** use of l1
  2 |     *** use of x
  2 |     *** (20,5) DEFINITE LAST FORWARDING USE OF *** use of x
  2 |     /scope
  1 |   /function

Note above the two "var x" in the same scope (same indent?).

Now, if we change the lambda's parameter to some other identifer, say `t`, viz.

`l1 := :(forward t) = {
        std::cout << f_inout(forward t) << std::endl;
    };`

we get the following sema `debug_print`:

  0 | function main
  1 |   scope
  2 |     var x
  2 |     /var 
  2 |     var l1
  2 |     var t
  2 |     scope
  3 |       *** (15,38) DEFINITE LAST FORWARDING USE OF *** use of t
  3 |       /scope
  2 |     /var 
  2 |     *** (18,5) DEFINITE LAST POTENTIALLY MOVING USE OF *** use of l1
  2 |     *** use of x
  2 |     *** (20,5) DEFINITE LAST POTENTIALLY MOVING USE OF *** use of x
  2 |     /scope
  1 |   /function

Now the resulting code correctly leaves the `++x;` alone:

````cpp
[[nodiscard]] auto main() -> int{
    auto x {21}; 

    auto l1 {[](auto&& t) -> void{
        std::cout << f_inout(CPP2_FORWARD(t)) << std::endl;
    }}; 

    std::move(l1)(x);

    ++x;
}
````

 I don't know enough about how cppfront handles scopes to be able to fix this.

**Comment by filipsajdak** [comment]
Thank you, @basic-bro, for your investigation!
