### ISSUE TITLE
[SUGGESTION] Make bitwise complement prefix like unary plus and minus

### ISSUE THREAD

**Issue by megajocke** [hsutter/cppfront#310]
I find it quite surprising and incosistent that bitwise ~ is postfix when unary - and + are prefix. I would have expected both of the mathematically similar ones' complement and two's complement operations to have similar placement in expressions and to match mathematical conventions. Both - and ~ tend to be used a lot in code working on bit masks, IO registers, etc.

Example:
```
main: () -> int = {
    x : uint32_t = 1;
    unary_plus := +x;
    twos_complement := -x;
    ones_complement := x~; // surprising

    fiddly := (-x) & (x~);
}
```

Making unary + and - postfix would be another way to remove the inconsistency, but this would not feel good unless one goes full Reverse Polish Notation in all expressions which would be quite far removed from C++ and most common languages...

**Comment by hsutter** [comment]
@msadeqhe Captured it pretty well. I did try making unary `+` and `-` postfix as well (which would have eliminated all prefix operators), and the main reason I relented and made them prefix again was because the very first thing that broke was `x := -1;`. There, the `-` is actually not part of the literal, it's an operator.

Truth be told, I sometimes still think of expanding the literal grammar to allow the prefix `-` (but not `+` - why support it? it's the default) as part of the literal itself, and then make the unary `+` and `-` operators postfix again. But that's really low priority compared to other things I want to work on so I haven't picked that idea back up yet.

Then again, comments like this (thanks!)

> I find it quite surprising and incosistent that bitwise ~ is postfix when unary - and + are prefix.

are feedback in favor of picking it up again and doing that... 😉

**Comment by hsutter** [comment]
So I'm leaving this issue open for now to see if anyone wants to argue in favor of that idea -- putting `-` in the literal grammar so `-10` still works, but otherwise making unary `+` and `-` postfix.

Note that the overwhelming use today for the prefix forms is in the negating-a-literal case. Other than that, they are very rarely used (yes, I know about the function pointer trick, that's super rare) so I conjecture that the vast majority of people would not even notice they're postfix...

**Comment by JohelEGP** [comment]
One thing that'd break is code injecting `"-(x)$"`. If `x` interpolates to a literal, it works. If not, you'd probably need to use a function instead, like `"(cpp2::negate_code(x))$"`. That smells funny, like `std::addressof`, `bool(x)`, and `(..., void(f(args)))`, to work around user-defined `operator&`, weird [_`boolean-testable`_](https://eel.is/c++draft/concepts#concept:boolean-testable) stuff, and user-defined `operator,`.

**Comment by msadeqhe** [comment]
> So I'm leaving this issue open for now to see if anyone wants to argue in favor of that idea -- putting `-` in the literal grammar so `-10` still works, but otherwise making unary `+` and `-` postfix.

It depends how much this would look like strange:

```
a := -10;
// x is 0
x := a - -10--;
```

However in reality no one would write code like that. Having postfix unary `+` and `-` seems reasonable enough for consistency:

```
a := -10;
// x is 0
x := a + 10;
// y is 10
y := x + a-;
```

Also for logical not, we could have an is not:

```
if true! {
    // It never happens.
}

If obj is! base {
    // If obj is not inherited from base...
}
```

**Comment by hsutter** [comment]
Re `!`: Ah yes, that's the other one I left prefix, and I think should be left prefix because of pervasive boolean expression familiarity.

**Comment by msadeqhe** [comment]
Unary postfix `+` and `-` are ambiguous with unary postfix `++` and `--`. For example:

```
x := 10;
// Is its value equal to 10 or 9?
x := x--;
// What is this?
x := x----;
```

**Comment by msadeqhe** [comment]
One possible solution to solve this issue, is to make unary postfix `++` and `--` to have higher precision than unary postfix `+` and `-`:

```
a := 10;

// := a-;
x1 := a-;

// := a--;
x2 := a--;

// := (a--)-;
X3 := a---;

// := (a--)--;
X4 := a----;

// := ((a--)--)-;
X5 := a-----;
```

**Comment by hsutter** [comment]
> Unary postfix `+` and `-` are ambiguous with unary postfix `++` and `--`. For example:

Actually they wouldn't be, because of [max munch](https://en.wikipedia.org/wiki/Maximal_munch). That is, during tokenization we take the longest match.

For example, `!=` always parses as a single token, it's never ambiguous with a `!` followed by an `=` as a space would be required to make it mean those two tokens.

**Comment by AbhinavK00** [comment]
I'd say keep it how it is now. @msadeqhe gave good reasons as to why current way makes sense.

**Comment by msadeqhe** [comment]
Well, first I'm trying to argue in favor of unary postfix `+` and `-`, after that I'm going to argue in favor of unary prefix `+` and `-`. In the following examples, all `x` variables are for unary postfix `+` and `-`, and all `y` variables are for unary prefix `+` and `-`.

### Why unary postfix `+` and `-` are better?

1. Consistency with unary postfix bitwise `~`

```
// OK. It seems consistent.
x0 := a-;
x1 := a~;

// OOPS! Why are they look different?
y0 := -a;
y1 := a~;
```

2. Left to right operator precedence

```
// OK. It seems natural.
x0 := a-~-~;

// OOPS! This one needs parenthesis:
y0 := --a~~;
// := (-((-a)~))~;
```

### Why unary prefix `+` and `-` are better?

1. Consistency with the sign of integer literals

```
// OOPS! Why are they look different?
x0 := a- + -10;

// OK. It seems consistent.
y0 := -a + -10;
```

2. Consistency with bitwise operators `+` and `-`

```
// OOPS!
x0 := b-;
x1 := a - b;

// OK. It seems natural.
y0 := -b;
y1 := a - b;
```

### Which one is better?

In my opinion, _left to right operator precedence_ is important, therefore unary postfix `+` and `-` have an upper hand over unary prefix `+` and `-` in that case.

**Comment by realgdman** [comment]
One of kind of legit use of prefix + is writing some vector/matrix stuff, like
`x = {{+a, -b}, {+a, +b},`
`     {-a, -b}, {-a, +b}};`
Of course that still can be formatted with whitespaces, but I always look cautiously at whitespaces because they can so easily lost with autoformatting, and IMO that looks little less elegant and noisy:
`x = {{ a, -b}, { a,  b},`
`     {-a, -b}, {-a,  b}};`

**Comment by msadeqhe** [comment]
According to [this issue](https://github.com/hsutter/cppfront/issues/319), C++2 grammer for operators could be easier to parse if unary `+` and `-` could be postfix, therefore all operators will be either binary or unary postfix, eliminating all unary prefix operators will simplify parser implementation. For example compare how parsing this code:
```
x := a-- - -b;
```
is harder than parsing this code:
```
x := a-- - b-;
```

In the second example, the symbol on the left side of `b` is always binary operator, but in the first example, it can be either binary or unary prefix operator.

**Comment by realgdman** [comment]
The thing with number is that we naturally write them as `-6`
So we have several options:
Write `6-` which looks weird
Write `-6` but `a-` which can lead to confusion
Write as it is now `-6` and `-a`
Actually there is another way to look at this problem. Ambiguity raises between `-` and `--`, so it could be `--` is culprit.
AFAIR Zig and maybe others took that route and banned `--`, so you have to write `a+=1`, and there is no problem parsing `a---b` because it is `a - -(-b)`.

**Comment by msadeqhe** [comment]
> Actually there is another way to look at this problem. Ambiguity raises between `-` and `--`, so it could be `--` is culprit.
> AFAIR Zig and maybe others took that route and banned `--`, so you have to write `a+=1`, and there is no problem parsing `a---b` because it is `a - -(-b)`. But that means losing some c++ idioms like `*srd++ = *src++`

Altough a white-space solves the ambiguity problem in C, C++, but I like the idea that `a+=1` and `a-=1` are general language feature and more meaningful than `a++` and `a--`.

**Comment by JohelEGP** [comment]
It also has a different precedence. `p++*` has to become `(p+=1)*`.

**Comment by hsutter** [comment]
Based on the feedback so far I'm going to close this as 'no action at this time,' but if there's new information or demand we can reopen it and I'll continue thinking about it (since I do want to make operators postfix wherever reasonable, especially if they are candidates for wanting to chain them). Thanks!

**Comment by msadeqhe** [comment]
@hsutter, What if C++2 supports unary postfix `+` and `-` in addition to unary prefix `+` and `-`? In this way one can simply use unary postfixes for operator chaining. For example:

```
x := 10;
y := -x;
z := x-~; // operator chaining
```

**With only one restriction that when an operand has unary postfix, it cannot have unary prefix `+` or `-`:**

```
x := 10;
y := -x;
z := -x~; // ERROR!
```

I think in this way C++2 will have both consistent unary postfix `-` and bitwise `~` (e.g. `x-` and `x~`), and consistency with integer literals (e.g. `-10` and `-x`) in addition to simple operator chaining with them.

**Comment by msadeqhe** [comment]
> With only one restriction that when an operand has unary **postfix**, it cannot have unary **prefix** `+` or `-`. This rule will prevent unary **prefix** `+` and `-` to be abused with unary **postfix** `+` and `-` (which of course prevents code ambiguity). Also this restriction almost satisfies the rule "don't have two ways to say the same thing".

To improve guidance, C++2 should categorize unary prefix `+` and `-` as sign operators, and unary postfix `+` and `-` as arithmetic operators. `operator+` and `operator-` will overload both prefix (sign) operators and unary postfix (arithmetic) operators.

**Comment by msadeqhe** [comment]
> With only one restriction that when an operand has unary postfix, it cannot have unary prefix + or -. This rule will prevent unary prefix + and - to be abused with unary postfix + and - (which of course prevents code ambiguity). Also this restriction almost satisfies the rule "don't have two ways to say the same thing".

Infact I think it's possible to remove this restriction without any problem.

### Alternative Solution

Sign operators are similar to unary prefix `+` and `-` operators with the following additional rules:

- They are exactly the same as their counterpart unary postfix `+` and `-`. For example:

```
n: = 2;

// +n and n+ are exactly the same.
a: = +n;
b: = n+;

// -n and n- are exactly the same.
x: = -n;
y: = n-;
```

- They cannot be applied multiple times to an operand. For example:

```
n: = 2;

// These are plus sign operators.
a: = +2; // OK
x: = +n; // OK.

// These are minus sign operators.
b: = -2; // OK.
y: = -n; // OK.

// Sign operators cannot be applied multiple times.
r: = ++n; // ERROR!
s: = --n; // ERROR!
t: = -+n; // ERROR!
u: = +-n; // ERROR!

// Also sign operators may be applied to parenthesis.
// Therefore you can use parenthesis to apply multiple sign operatros.
i: = +(+n); // OK.
j: = -(-n); // OK.
k: = -(+n); // OK.
l: = +(-n); // OK.
```

- They have higher operator precedence than almost other operators. For example:

```
n: = 2;

a: = -n--; // It's exactly equal to (-n)--;
a: = -n-~; // It's exactly equal to ((-n)-)~;
```

- Overloading `operator+` and `operator-` will overload both sign operators `+` and `-` and unary postfix operators `+` and `-`.

Both sign operators (unary prefix `+` and `-`) and unary postfix `+` and `-` are necessary to have operator chaining while keeping the consistency of operators, because:

- Integer literals have sign `+` or `-`. Variables should have sign operators (unary prefix `+` and `-`) to keep consistency with literals.

- On the other hand, variables should have unary postfix `+` and `-` to have operator chaining while keeping consistency with bitwise `~`.

I should mention that C++2 somehow unified literals and variable for function call `2.call()` and `x.call()`, they should be the same for sign `+` and `-` too (e.g. `+2` and `+x`). Unary postfix `+` and `-` will complement these relationship to have consistency with bitwise `~`, and to enable easier operator chaining.

So if we remove that restriction, the example will be changed like this:

```
x := 10;
y := 10-; // OK. It's an operator -
z := -10-; // OK. (-10)-;
b := -x-; // OK. (-x)-;
c := -x~; // OK. (-x)~;
d := -x--~; // OK. ((-x)--)~;
```

**Comment by megajocke** [comment]
Sorry for not noticing the interesting activity here. I was thinking of the conventions used in mathematics for [boolean algebra](https://en.wikipedia.org/wiki/Boolean_algebra) where although other symbols are traditionally used, it does follow the same prefix/infix conventions as arithmetic.

```
Arithmetic:    -       +           *
Logical:       !       ||          && 
Bitwise:       ~       | and ^     &
```

One can consider  ~ to be the bitwise equivalent to - or ! just like & is the bitwise equivalent to * or &&.

**Comment by msadeqhe** [comment]
So making `~` to be a prefix, is the easiest (and perhaps the most reasonable) way to eliminate inconsistency, because both `-` and `!` are already prefix. Making unary prefix operators to have the highest operator precedence, helps to simplify the combination rule of unary prefix and postfix operators because unary prefix operators aren't frequency used in operator chaining.
