### ISSUE TITLE
[SUGGESTION] As a software developer I want to use line spaces to specify scope similarly to python 

### ISSUE THREAD

**Issue by fro0m** [hsutter/cppfront#347]
Goal: simplify syntax, make it better readable and less space taking

In the original C++ syntax such spaces will be converted to curly braces. Both syntax would be valid. 
It should work not for only one-line functions, but also for blocks and blocks inside blocks. It is the concept when indentation means logical blocks, not only syntax. It is the way to simplify syntax when conveying the same logical intent.

Just a minimal example:
![image](https://user-images.githubusercontent.com/3215404/230920897-dde7a4c0-1dd4-4fb1-ad32-d8400c305b65.png)
equals
![image](https://user-images.githubusercontent.com/3215404/230921097-c9bac992-a8a6-4a0a-b9c8-6ab48192e30d.png)

**Comment by filipsajdak** [comment]
This is short form of functions - it is not about spaces like in python.

```cpp
fun: () -> int = 42; // fun that returns 42
```

```cpp
fun: (i:int, j:int) -> int = i+j; // function that returns sum of arguments i + j
```

```cpp
print: (x) = std::court << x << std::endl; // function that prints argument
```

**Comment by fro0m** [comment]
> This is short form of functions - it is not about spaces like in python.
> 
> ```c++
> fun: () -> int = 42; // fun that returns 42
> ```
> 
> ```c++
> fun: (i:int, j:int) -> int = i+j; // function that returns sum of arguments i + j
> ```
> 
> ```c++
> print: (x) = std::court << x << std::endl; // function that prints argument
> ```

Thank you for the attention to my suggestion. Is it possible to write multi-line functions and logical blocks inside logical blocks without curly braces?
example:
```
fun: (i:int, j:int) -> CODES = 
     std::lock_guard<std::mutex> lock(x_mutex);
     x: i + j;
    std::cout << x << std::endl;
  CODES::SUCCESS
```
versus
```
fun: (i:int, j:int) -> CODES = {
    {
          std::lock_guard<std::mutex> lock(x_mutex);
          x: i + j;
          std::cout << x << std::endl;
    }
    CODES::SUCCESS
}
```

**Comment by JohelEGP** [comment]
No.

**Comment by JohelEGP** [comment]
I'm working on Clang-Format support for Cpp2 right now. I can't imagine it working as well without braces for multi-statement blocks.

**Comment by realgdman** [comment]
Whitespace indentation feels more error prone to me. For this code
`if(b == 1)`
`	fooA();`
`	fooB();`
Clang -Wall gives warning about misleading indentation, because it has to be either only one statement after `if`, or { block }.
In Python-like language there is no way for tooling to detect this kind of typos, because both of those could be valid:
`if b:`
`	fooA()`
`	fooB()`
or
`if b:`
`	fooA()`
`fooB()`

**Comment by gregmarr** [comment]
I will say right out that I can not say how strongly I dislike languages where the amount of whitespace (rather than merely the presence/absence of whitespace, so mainly indentation) is significant.

**Comment by fro0m** [comment]
> Whitespace indentation feels more error prone to me. For this code `if(b == 1)` ` fooA();` ` fooB();` Clang -Wall gives warning about misleading indentation, because it has to be either only one statement after `if`, or { block }. In Python-like language there is no way for tooling to detect this kind of typos, because both of those could be valid: `if b:` ` fooA()` ` fooB()` or `if b:` ` fooA()` `fooB()`

1. Most of Python IDEs show a warning when there is an issue with an identation.
2. With your `if` example you have shown the exact problem of original C++ syntax when a software developer confuses himself with meaningless of indentation in the original C++. If the indentation would mean something, than  software developers always keep in mind that they either write everything inside a block with the same indentation or embrace the block with curly braces.

There is not much sense in using curly braces because programmers have to anyway make double work of placing curly braces and spaces until some tool like clang-format aligns spaces against curly braces.

Add to that, no curly braces (alternative) syntax looks much more compact, better looking and **much more aligned with the minimalistic style of cpp2**:
```
fun: (i:int, j:int) -> CODES = 
     std::lock_guard<std::mutex> lock(x_mutex);
     x: i + j;
     std::cout << x << std::endl;
  CODES::SUCCESS
```

**Comment by orent** [comment]
I have been using python for decades and I absolutely love it - but my reaction to this suggestion is an emphatic NO.

**Comment by robertefry** [comment]
Please don't let space characters become part of the language. That would screw up a lot of descriptive formatting.

Though short-form functions might be a good call, this is not the same as tokenising spaces/tabs.
```cpp
f: (x: int, y: int) -> int = x + y;

f: (x: int, y: int) -> int = { return x + y; }

int f(int x, int y) { return x + y; }
```

**Comment by fro0m** [comment]
You can not reject the objective fact, that code without `{}` much more compact and better readable. And this is what makes Python n1 in most language ratings (at this moment) as it does not make developers to do extra work with writing useless semantics.

```
fun: (i:int, j:int) -> CODES = 
     std::lock_guard<std::mutex> lock(x_mutex);
     x: i + j;
     std::cout << x << std::endl;
  CODES::SUCCESS
```
versus
```
fun: (i:int, j:int) -> CODES = {
    {
          std::lock_guard<std::mutex> lock(x_mutex);
          x: i + j;
          std::cout << x << std::endl;
    }
    CODES::SUCCESS
}
```

**Comment by filipsajdak** [comment]
I will cite Herb here (you can find it in a Suggestion template)

> - _Please do not suggest syntax changes._ I accept there are hundreds of opinions and everyone will prefer something a little different. Syntax isn't the big thing, fixing semantics is -- reducing concept count, increasing toolability, are the big payoff.
> - _Please do not suggest things that amount to personal taste._ I accept there are hundreds of personal tastes and everyone will prefer something a little different.

I think I strongly support this part “I accept there are hundreds of opinions and everyone will prefer something a little different. Syntax isn't the big thing, fixing semantics is”

There is plenty of areas for improvement. The time is limited and not every topic deserves to spend time on it. This one, I believe, will not make the language 10x safer or easier.

**Comment by SebastianTroy** [comment]
When programming a larger project, that will live for a long time, the certainty that the scope of some code is attributed to a particular branch, or fine controlling the lifetime of an object in a clear and concise manner (IMO) far outweighs the milliseconds saved from skipping a few braces.

Whitespace based scoping has pitfalls. It is especially confusing when some whitespace is important, and some isn't (line wrapping is still possible in python and that whitespace isn't important?)

In C++ RAII is also important, and explicit scoping is really important in many situations


On 15 April 2023 08:13:55 Konstantin F ***@***.***> wrote:

You can not reject the objective fact, that code without {} much more compact and better readable. And this is what makes Python n1 in most language ratings (at this moment) as it does not make developers to do extra work with writing useless semantics.

fun: (i:int, j:int) -> CODES =
     std::lock_guard<std::mutex> lock(x_mutex);
     x: i + j;
     std::cout << x << std::endl;
  CODES::SUCCESS


versus

fun: (i:int, j:int) -> CODES = {
    {
          std::lock_guard<std::mutex> lock(x_mutex);
          x: i + j;
          std::cout << x << std::endl;
    }
    CODES::SUCCESS
}

**Comment by hsutter** [comment]
@fro0m, you're in good company -- you aren't the first to suggest significant whitespace. And I like Python too!

I'm going to take a hard line on this question... on both sides. 😁

I agree with @fro0m that Python's approach fixes a problem in C and C++ code, where inadvertent indentation mistakes can happen for single-statement `if`/`else` branch bodies, especially with macro expansion that turns what looks like one statement into multiple statements (and only the first one staying in the branch body). Fortunately, going all the way to (foreign-to-C-and-C++-programmers) significant whitespace/indentation isn't the only way to fix it... Cpp2 takes this problem seriously, and exactly for this reason requires the `{` `}` braces around branch bodies. Granted, that's going exactly the opposite direction you ask for, @fro0m, but it's the consistent way and also allows making `(` `)` around branch (and loop) conditions optional.

Given that mandatory `{` `}` around branch and loop bodies solves that real problem, I don't see a need to support significant whitespace in Cpp2, and I actually see major downsides... I'll go back to [what I said in the talk here](https://youtube.com/clip/UgkxBBccZc2batJBuzvLx9INcSfljpwzYh2Y).

Consider that if we did do significant whitespace, there would be two ways to do it, but both of them would violate core design principles of Cpp2:
- **Do it in addition to `{` `}` blocks.** I won't do that because of the Cpp2 design stake that we should avoid providing two (competing, inconsistent, etc.) ways to do the same thing. A designer of a language (or of anything) has the job of making decisions... when they leave two ways to do the same thing, they may say "we're letting the user decide," but more often than not it really means they're abdicating their responsibility to make the decision, to do their job. 
- **Do it instead of `{` `}` blocks.** I won't do that because of the Cpp2 design stake to stick with fixing known safety and complexity problems in C++ (and C), ad avoid making "drive-by improvements"... and especially minimizing even surface divergence from C++ where it doesn't carry its weight by solving such problems. Switching to significant whitespace would also be a much deeper change, because if whitespace is significant in branches and loops, it should be significant everywhere in the language, which is a fundamental change. 

So I appreciate the suggestion, and you're in good company -- some big names in the industry have asked me to use significant whitespace for block indentation! -- but I'm going to stick to my guns on this one.

Thanks, and thanks for understanding!

**Comment by gregmarr** [comment]
> You can not reject the objective fact, that code without {} much more compact and better readable.

I accept the objective fact that code without {} *can be* much more compact, depending on your style.  It doesn't have to be, though.  The difference between having braces and not having braces can be as little as one additional line for an entire `if`/`else if`/`else` block.

I do however reject that it *is* an objective fact that it is "better readable".  This is purely an opinion, and one which others don't share.

I support Herb's view of "minimizing divergence" where it doesn't solve a safety and complexity problem, especially where there is a method that minimizes that divergence and solves the same problem at the same time.

**Comment by msadeqhe** [comment]
> You can not reject the objective fact, that code without `{}` much more compact and better readable. And this is what makes Python n1 in most language ratings (at this moment) as it does not make developers to do extra work with writing useless semantics.

White-sapce significant block statement is limited compared to `{...}` block statement. That's why Python cannot have statements inside expressions. For example, Python cannot have multi-line lambda which is specified in Python language reference documention:

```
Note that functions created with lambda expressions cannot contain statements or annotations.
```

For another example, also something like this is not possible in Python:

```
x: = if condition {
    ...
    return value;
}
else {
    ...
    return another_value;
}
```

**Comment by hsutter** [comment]
BTW, because there really are benefits with both braces and significant whitespace indentation and a language just has to choose one path or the other, the Python designers are in a similar pickle -- they similarly get regular requests to add `{` `}` braces!

To the point where they put an Easter Egg in Python... try `from __future__ import braces` in Python. 😁
