### ISSUE TITLE
[BUG] does not bounds check iterators

### ISSUE THREAD

**Issue by grizzlysmit** [hsutter/cppfront#51]
the following code segfaults:
using  `while first <= last {` instead of `while first < last {`  

**To Reproduce**
1.
```cpp2
main: () -> int
= {
    words: std::vector<std::string> = ( "decorated", "hello", "world" );

    first: std::vector<std::string>::iterator = words.begin();
    last : std::vector<std::string>::iterator = words.end();

    while first <= last {
        print_and_decorate(first*);
        first++;
    }
}

print_and_decorate: (thing:_) =
    std::cout << ">> " << thing << "\n";

```

2.
```sh
 $ cppfront  pure2-bounds-safety-iterator.cpp2 -p -s
pure2-bounds-safety-iterator.cpp2... ok (all Cpp2, passes safety checks)

 $ g++ -std=c++20 pure2-bounds-safety-iterator.cpp -o pure2-bounds-safety-iterator
 $ ./pure2-bounds-safety-iterator 
>> decorated
>> hello
>> world
Segmentation fault (core dumped)
 ```
3. I wanted cppfront to reject it 

4. it it passed and segfaulted on running

**Comment by hsutter** [comment]
Correct. Currently cppfront:
- bans pointer arithmetic for pointerlike types that it knows about, but right now that's just explicitly declared local pointer variables in Cpp2 function bodies (in the future I'll teach it about STL iterator types and other Pointer-like types -- see [Lifetime profile](https://github.com/isocpp/CppCoreGuidelines/blob/master/docs/Lifetime.pdf) section 2.1 for the `Pointer` type category which includes iterators)
- adds dynamic bounds checking for indexed accesses (but not iterators) if you enable it using the `-subscript-checks` switch

The long-term goal is to treat STL iterator arithmetic like pointer arithmetic -- i.e., as unsafe because iterators don't know their bounds (in the standard, modulo that some STL debug implementations do attempt to add bounds/invalidation checks).
