### ISSUE TITLE
[BUG] Short function syntax with multiple return values generates bad code.

### ISSUE THREAD

**Issue by filipsajdak** [hsutter/cppfront#55]
Having a single expression function that uses multiple return values syntax compiles to bad cpp1 code.
```cpp
fun: () -> (i:int) = i = 42;
```

## Steps
```
tests % cppfront ufcs.cpp2 
ufcs.cpp2... ok (all Cpp2, passes safety checks)

tests % clang++ -std=c++20 -I../cppfront/include ufcs.cpp
tests/ufcs.cpp2:24:47: error: use of undeclared identifier 'i'
[[nodiscard]] auto fun() -> fun__ret { return i.construct(42); }
                                              ^
1 error generated.
```

## Expected result

It should fail on cppfront or compile to correct code like:
```cpp
[[nodiscard]] auto fun() -> fun__ret{
  cpp2::deferred_init<int> i;
  i.construct(42);
  return  { std::move(i.value()) }; 
}
```

## Actual result/error

cppfront generates bad code that fails to compile:
```cpp
[[nodiscard]] auto fun() -> fun__ret { return i.construct(42); }
```

Compiler version
```
tests % clang++ --version
Apple clang version 14.0.0 (clang-1400.0.29.102)
Target: arm64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by AlexanderLanin** [comment]
The trouble is `function_prolog` is printed in `emit` of `compound_statement_node`, but the short syntax doesnt have a compound statement. The function scope is generated directly within `emit` of `expression_statement_node`. Seems like a hack?

I don't understand enough of cppfront to actually fix it. Maybe every function should have an enforced `compound_statement_node`? Otherwise `function_prolog` and `function_epilog` are never printed in short syntax. This might remove the need to print braces within `emit` of `expression_statement_node`. Alternatively pass `function_prolog` and `function_epilog` to `emit` of `expression_statement_node` and print them there...

P.S. It would have really simplified things if all the emit functions had unique names like `emit_expression_statement_node` as VS Code does not jump to the correct emit function when ctrl+clicking on it.

**Comment by filipsajdak** [comment]
`emit` is used in generic context like

```cpp
template <int I>
auto try_emit(auto& v, auto... more) -> void {
  if (v.index() == I) {
    auto const& alt = std::get<I>(v);
    assert (alt);
    emit (*alt, more...);
  }
}
```
(`v` is variant) emit functions must have the same name if they work in such a context. 

I have been learning cppfront structure. What helped me the most was using the debugger and following the code flow. 

I must warn you that the class hierarchy is very nested, and you will go via the same function multiple times (every call will happen in a different context). In the beginning, it looked like it was in an infinite loop but had its end.

**Comment by hsutter** [comment]
> Having a single expression function that uses multiple return values syntax compiles to bad cpp1 code.
> `fun: () -> (i:int) = i = 42;`

Right you are, and after thinking about it I think that the short body syntax should just not be allowed if you have named return value(s). That wouldn't work with multiple named return values anyway, which would require multiple statements to assign them. And the short body syntax is mainly for simple functions that produce `void` or a single value. Thanks!
