### ISSUE TITLE
[BUG] New terse function syntax requires adding a semicolon after expression

### ISSUE THREAD

**Issue by gregmarr** [hsutter/cppfront#760]
**Describe the bug**
A trailing semicolon is required when dropping the `-> _ =` from an inline lambda expression used inside a function call.

**To Reproduce**
1. Sample code - distilled down to minimal essentials please

```
    // okay
    std::transform(a.begin(), a.end(), b.begin(), :(x) -> _ = { return x + 1; });

    // remove "{ return" and "; }", okay
    std::transform(a.begin(), a.end(), b.begin(), :(x) -> _ = x + 1);

    // remove "-> _ =", error: invalid statement encountered inside a compound-statement (at 'x')
    std::transform(a.begin(), a.end(), b.begin(), :(x) x + 1);

    // put back the ";", okay
    std::transform(a.begin(), a.end(), b.begin(), :(x) x + 1;);
```

2. Command lines including which C++ compiler you are using
https://www.godbolt.org/z/6T9z4nx88

3. Expected result - what you expected to happen
Successful compilation.

4. Actual result/error
error: invalid statement encountered inside a compound-statement (at 'x')

**Additional context**
[#714 
](https://github.com/hsutter/cppfront/discussions/714#discussioncomment-7277271)

**Comment by hsutter** [comment]
How about that... somehow I had in my head that the `;` was always required. I'm a little surprised that the second example works... perhaps it's looking for any valid _expression_ (which would maximally grab as much as could be a valid expression, which could include an _expression_statement_) rather than specifically an _expression-statement_.

Well, for the terse syntax I just changed the check to see if there was a valid _expression_ instead of _expression-statement_ and all seems to be well. Let's try it. Saves another character on the tersest syntax...

Also, just to make sure it still works on a non-first argument, this is fine too now with the latest commit above:

```
main: () = {
    a: std::vector<int> = (1, 2, 3);
    b: std::vector<int> = (7, 8, 9);

    test( :(x) x + 1, a, b );

    for b do (e) std::cout << e;
}

test: (c, a, inout b) =
    std::transform(a.begin(), a.end(), b.begin(), c);
```

Thanks!
