### ISSUE TITLE
[BUG] Passing lambda to function call of for loop causes incorrect uninitialized variable error

### ISSUE THREAD

**Issue by KendallHarter** [hsutter/cppfront#778]
**Describe the bug**
Passing a lambda to a for loop parameter's function call produces an incorrect "use before initialization" error.

**To Reproduce**
Sample code:
```
first: (forward f, forward _...) -> forward _ = f;

main: () = {
   ints: const std::array = (1, 2, 3, 4, 5);
   // OK
   for ints.first() do (i) {
      std::cout << i;
   }

   // OK
   for ints.first(1) do (i) {
      std::cout << i;
   }

   // Error
   for ints.first(:(x) x) do (i) {
      std::cout << i;
   }

   // OK
   temp := ints.first(:(x) x);
   for temp do (i) {
      std::cout << i;
   }
}
```

Commands:
```
./cppfront test.cpp2
```

Expected result:
Program compiles without error.

Actual result/error:
```
test.cpp2...
test.cpp2(17,20): error: local variable i is used before it was initialized
  ==> program violates initialization safety guarantee - see previous errors
```

**Additional context**
I found this while trying to use `std::views::filter` and this seems to be the root cause of the error.

**Comment by fknauf** [comment]
I fired up ye olde debugger and took a look. The problem is that when the for loop parameter is processed in `sema::start(declaration_node const&, int)`, the variable `just_entered_for` is `false` when it should be true.

AFAICT this happens because it is set to `true` directly after the `for` token is processed, and because then the processing of the lambda puts it back to `false`. I think the fix is to set `just_entered_for` to `true` between

```
        range->visit(v, depth+1); // this processes ints.first(:(x) x), afterwards just_entered_for is false
        // here it needs to be set to true
        parameter->visit(v, depth+1); // then this processes (i)
```
in `iteration_statement_node::visit(auto& v, int depth)`. 

I'll try to put together a fix.

**Comment by JohelEGP** [comment]
This is #432.
