### ISSUE TITLE
[BUG] Missing return statement should be a compiler error

### ISSUE THREAD

**Issue by simeonKuran** [hsutter/cppfront#820]
I don't know, if this is a bug or a suggestion.

**Description** 
It would be great, if cppfront could detect missing return statements.

**To Reproduce**

```
test: () -> int = {}  // at least triggers a warning
main: () -> int = { } // no warning, no error
```
**Expected Result**
A Compile error for both lines would be appreciated with a diagnostic message, that the return statement (of type int) is missing.

**Actual Result**
The test function results in a compiler warning (in the lowered cpp1), the main compiles successfully without any warning.

**Additional Info**
I am using g++ 11.4.0 on Linux

**Comment by JohelEGP** [comment]
Maybe the return value can be semantically treated as an uninitialized variable that is initialized by a return statement.
For example, have `test0: () -> int = { }` and `test1: () -> int = { return 0; }` be semantically treated as:
```Cpp2
test0: () -> (res: int) = { } // error: `res` is left uninitialized.
test1: () -> (res: int) = { res = 0; return; } // OK
```

**Comment by gregmarr** [comment]
C++ does not require a return statement in `main`.  Also, I believe that if you've named your return variables, the `return` statement is optional.

**Comment by JohelEGP** [comment]
Still, I would like `assert(false);` to disable such requirement.

```Cpp2
  to_camel_case: (s: std::string_view) -> std::string = {
    if s.is_snake_case() {
      return s.std::views::split('_');
    }
    assert(false, "Only `snake_case` is supported.");
  }
```

For the complexity in this area, see <https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/p2806r1.html#control-flow>.

**Comment by gregmarr** [comment]
This looks like it should be a precondition, so it's not UB.

```
  to_camel_case: (s: std::string_view) -> std::string pre(s.is_snake_case()) = {
    return s.std::views::split('_');
  }
```

**Comment by JohelEGP** [comment]
I'm still writing the function.
So it's a real use case for wanting to turn off the required `return`.
It's definitely not a contract.
I really wanted to use `std::unreachable();`,
but I want to avoid UB.

**Comment by gregmarr** [comment]
What do you want to happen if you do get there?  Are you sure that it's impossible to get there, and you just want to let the compiler know that you're sure?  That sounds like `std::unreachable()` to me.

**Comment by gregmarr** [comment]
I guess that would be

```
assert(false, "shouldn't get here"); // or in c++26 contract_assert(false);
std::unreachable();
```

**Comment by JohelEGP** [comment]
I tried `std::unreachable();` alone to workaround `warning: non-void function does not return a value in all control paths [-Wreturn-type]`.
That really just crashes without any useful input.
In QtCreator, I do get
![1699997623](https://github.com/hsutter/cppfront/assets/21071787/eb3e4154-43d7-4933-826c-c6b3f624bf88)
As you say, I suppose I'll need the `std::unreachable()`.
I probably would, anyways, if someone replaced the default handler to ignore, if that's possible.
Thank you.

**Comment by simeonKuran** [comment]
Granted, there are some use cases were we explicitly don't want a return statement. (e.g. `std::unreachable()`, named return variables, etc).

I appreciate that idea:
> Maybe the return value can be semantically treated as an uninitialized variable that is initialized by a return statement. For example, have `test0: () -> int = { }` and `test1: () -> int = { return 0; }` be semantically treated as:
> 
> ```
> test0: () -> (res: int) = { } // error: `res` is left uninitialized.
> test1: () -> (res: int) = { res = 0; return; } // OK
> ```

However, as already pointed out, a return statement is optional for main and for other functions a warning is already emitted. (and with -Werror it can be transformed into an error)

Mabye, that's good enough? 
I tend to close this ticket...

**Comment by gregmarr** [comment]
I would tend to leave it for Herb to take a look at and see if there's anything he wants to do here.  He might already have thoughts.

**Comment by hsutter** [comment]
Thanks for the suggestion! I'm inclined to stay with status quo on this one, sorry, but I appreciate the idea.

Longer answer:

I personally like default returns when there's a sensible default. There are two cases where Cpp2 intentionally has a default implicit `return`, when you could not have meant anything else:
- For `main: () -> int`, Cpp2 uses the Cpp1 default of `return 0;`. (See further notes about `main` below, this comes up a lot less in Cpp2 because `-> int` is neither required nor default.)
- For `operator=: (inout this, /*...*/)` (assignment), Cpp2 adds the new default of `return *this;`.

And then the third case:
- For all other functions, every Cpp1 compiler I know of already gives a diagnostic on most non-void-returning functions that are missing a return statement, including the example at top. So the Cpp2 code already gets the diagnostic, it happens to come from the Cpp1 compiler but it still references the `.cpp2` file and source location.

Further on `main`... `main` has two issues/surprises in Cpp1, where I think the first is the big one:

1) In Cpp1, `main` *must* return `int`. But people keep trying write it to return `void` and we keep having to explain "it just has to be `int`, just write it, technically anything else is illegal." That not very satisfying when the programmer doesn't care about the return value, doesn't know what it even means, and may even be targeting an environment where it doesn't have a meaning.

2) In Cpp1 (and Cpp2), when you do write `int` you get an implicit `return 0;`. I do see that still occasionally generating questions, but in my experience not as much as (1), and often after the person first hits (1).

In Cpp2, (1) is already eliminated: Not only is `main` allowed to return `void`, but it's the default(!) as for all functions. So the major source of surprise is already gone which also removes many cases of (2).

> A Compile error for both lines would be appreciated with a diagnostic message, that the return statement (of type int) is missing.

As I mentioned, the Cpp1 compilers already do this in general for this case. My general rule for errors where the Cpp1 compilers all already gives a good diagnostic is that I don't do extra work just to move the diagnostic to cppfront.

**Comment by simeonKuran** [comment]
Thx for the long answer! 😊 👍
Sounds promising to me. So I think the issue can be closed now.
