### ISSUE TITLE
Lambdas that modify their closure: &$*

### ISSUE THREAD

**Issue by wolfseifert** [hsutter/cppfront#833]
When porting lambdas that modify their closure from Cpp1

<pre>
#include &lt;iostream&gt;
using namespace ::std;
int main() {

  auto x = 5;
  auto y = 7;

  auto v = [&amp;] {
    auto z = x;
    x = y;
    y = z;
  };

  cout &lt;&lt; "x = " &lt;&lt; x &lt;&lt; ", y = " &lt;&lt; y &lt;&lt; endl;
  v();
  cout &lt;&lt; "x = " &lt;&lt; x &lt;&lt; ", y = " &lt;&lt; y &lt;&lt; endl;
}
</pre>

to Cpp2 the syntax gets pretty ugly

<pre>
main: () = {
  using namespace ::std;

  x := 5;
  y := 7;

  v := :() = {
    z := x$;
    x&amp;$* = y$;
    y&amp;$* = z;
  };

  cout &lt;&lt; "x = (x)$, y = (y)$" &lt;&lt; endl;
  v();
  cout &lt;&lt; "x = (x)$, y = (y)$" &lt;&lt; endl;
}
</pre>

This &amp;$* was the only way I found to make it work.
<p>
When doing the same for nested lambdas

<pre>
#include &lt;iostream&gt;
using namespace ::std;
int main() {

  auto x = 5;
  auto y = 7;

  auto v = [&amp;] {
    auto w = [&amp;] {
      auto z = x;
      x = y;
      y = z;
    };
    w();
  };

  cout &lt;&lt; "x = " &lt;&lt; x &lt;&lt; ", y = " &lt;&lt; y &lt;&lt; endl;
  v();
  cout &lt;&lt; "x = " &lt;&lt; x &lt;&lt; ", y = " &lt;&lt; y &lt;&lt; endl;
}
</pre>

it gets even worse

<pre>
main: () = {
  using namespace ::std;

  x := 5;
  y := 7;

  v := :() = {
    x2 := x&amp;$;
    y2 := y&amp;$;
    w := :() = {
      z := x2$*;
      x2$* = y2$*;
      y2$* = z;
    };
    w();
  };

  cout &lt;&lt; "x = (x)$, y = (y)$" &lt;&lt; endl;
  v();
  cout &lt;&lt; "x = (x)$, y = (y)$" &lt;&lt; endl;
}
</pre>

This nested lambda example may seem artifical, but appeared when porting a real Cpp1 program over to Cpp2.
<p>
Is there any better syntax for this available? Do I miss something?

**Comment by msadeqhe** [comment]
That's it. It's the syntax of capture by pointer in Cpp2.

This topic is related to issue #247.

**Comment by AbhinavK00** [comment]
cpp2 should have a feature for reference capture, maybe captures could even be defined in terms of parameter passing conventions. I don't know why Herb didn't want to support capture by reference, maybe because of safety concerns but the current idiom isn't safer in any way.

**Comment by SebastianTroy** [comment]
I've noticed the &$* syntax mentioned a couple of other times and really really hated it, and just hoped it would not really need to make an appearance in production code.

I don't think the additional capture block in cpp1 was really all that bad, could we add an optional capture block before or after) the parameter block, and then as was mentioned before, use normal parameter passing syntax to define whether it is a copy or reference?

myLambda : (copy y)$ (x) x + y;

The capture block makes it clearer IMO that values are being captured in a way that might leave them dangling unless you pay attention, also in the case where you use the same captured variable multiple times you can't accidentally capture by copy in one place and reference/pointer in another, unless you really meant to.

There's no reason to prevent normal functions from having a capture block, honestly I'd prefer to have to manually capture global variables in the few cases o use them, to prevent accidental modifications with wide ranging side effects, and to make wide ranging side effects really visible in the code.

I know a lot of people are pushing for terser and terser syntax at the moment, but for the most part, C++ is a complex language, not a scripting language, and I'd rather type a few more characters if it added nice signposts to my code, allowing me to parse it visually more easily, and flag important things where they are happening.


On 15 November 2023 07:48:29 Abhinav00 ***@***.***> wrote:

cpp2 should have a feature for reference capture, maybe captures could even be defined in terms of parameter passing conventions. I don't know why Herb didn't want to support capture by reference, maybe because of safety concerns but the current idiom isn't safer in any way.

**Comment by JohelEGP** [comment]
> I know a lot of people are pushing for terser and terser syntax at the moment, but for the most part, C++ is a complex language, not a scripting language, and I'd rather type a few more characters if it added nice signposts to my code, allowing me to parse it visually more easily, and flag important things where they are happening.

We can have the best of both worlds.
The lack of ceremony also means that what is relevant stands out more.
I'm a fan of `:(x) x + y$`, as the parameterized nature of the expression stands out more.

Also, `post(size() == size()$ + 1)` is fantastic.
You don't need to give `size()` a name and then use it.
And the `o.type()$` in `sfml_types.std::ranges::any_of(:(x) o.type()$.starts_with(x))` (<https://github.com/hsutter/cppfront/discussions/789#discussioncomment-7572313>)
is performant; it is captured once and used _`N`_ times.

**Comment by SebastianTroy** [comment]
:(x) x + y$ is certainly terse, but does it scan easily in a large codebase as a lambda?

Also this limits capture to copy only, or at least be defined by the author, rather than allow the compiler to decide / optimise.

Take this made up syntax for example, if we allowed adding captures to the parameter list to signal that they follow the same rules (the in is default but included to emphasise what would be possible)

:(x, in y$) x + y

Might require double naming, but would give the author the ability to signal intent, rather than implement specifics. Here the compiler can decide whether it is better to capture by reference or copy.

If I need to make sure the captured variables stay in scope I can specify move or copy as required. Also changing the name can sometimes be beneficial,

:(x, in y$ = someReallyLongName) x + y / y ^ y

As to your mention of performance, I don't see how postfix $ is changing performance in your example, it is identical to cpp1 [t = o.type()], and so would perform the same right?



On 15 November 2023 13:42:56 Johel Ernesto Guerrero Peña ***@***.***> wrote:

I know a lot of people are pushing for terser and terser syntax at the moment, but for the most part, C++ is a complex language, not a scripting language, and I'd rather type a few more characters if it added nice signposts to my code, allowing me to parse it visually more easily, and flag important things where they are happening.

We can have the best of both worlds.
The lack of ceremony also means that what is relevant stands out more.
I'm a fan of :(x) x + y$, as the parameterized nature of the expression stands out more.

Also, post(size() == size()$ + 1) is fantastic.
You don't need to give size() a name and then use it.
And the o.type()$ in sfml_types.std::ranges::any_of(:(x) o.type()$.starts_with(x)) (#789 (reply in thread)<https://github.com/hsutter/cppfront/discussions/789#discussioncomment-7572313>)
is performant; it is captured once and used N times.

**Comment by JohelEGP** [comment]
> As to your mention of performance, I don't see how postfix $ is changing performance in your example, it is identical to cpp1 [t = o.type()], and so would perform the same right?

That's right.
But you have to give it a name far from its use,
which isn't necessarily an improvement.

**Comment by JohelEGP** [comment]
> ```Cpp2
>   v := :() = {
>     x2 := x&$;
>     y2 := y&$;
>     w := :() = {
>       z := x2$*;
>       x2$* = y2$*;
>       y2$* = z;
>     };
>     w();
>   };
> ```

Capture the function expression instead (<https://cpp2.godbolt.org/z/zne45Pb6o>):
```Cpp2
main: () = {
  using namespace ::std;

  x := 5;
  y := 7;

  v := :() = {
    w := :() = {
      z := x&$*;
      x&$* = y&$*;
      y&$* = z;
    }$;
    w();
  };

  cout << "x = (x)$, y = (y)$" << endl;
  v();
  cout << "x = (x)$, y = (y)$" << endl;
}
```
```output
Program returned: 0
x = 5, y = 7
x = 7, y = 5
```

**Comment by JohelEGP** [comment]
> Also this limits capture to copy only, or at least be defined by the author, rather than allow the compiler to decide / optimise.

I recall reading the same comment on Cpp1 lambdas.
As Cpp2 demonstrates, explicit is better than implicit.
There are examples in Cpp1 where "leaving it to the optimizer" has not proven itself for ranges of users.
I recall TD[EH][] and [HALO][].
Please, share the others.

[ABI]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#abi-api
[ADL]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#adl
[CNTTP]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#cnttp
[CPO]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#cpo
[CRTP]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#crtp
[CTAD]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#ctad
[WG]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#cwg-ewg-ewgi-lewg-lewgi-lwg
[SG]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#cwg-ewg-ewgi-lewg-lewgi-lwg
[EH]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#eh-tdeh
[HALO]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#halo
[ICE]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#ice
[IFNDR]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#ifndr
[II]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#iile
[NSDMI]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#nsdmi
[NTTP]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#nttp
[ODR]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#odr
[PIMPL]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#pimpl
[QoI]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#qoi
[RVO]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#rvo-nrvo-urvo
[SBO]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#sbo-soo-sso
[SCARY]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#scary-iterators
[SFINAE]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#sfinae
[SMF]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#smf
[STL]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#stl
[TMP]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#tmp
[TU]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#tu
[UB]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#ub
[UDL]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#udl
[UFCS]: https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#ufcs

**Comment by SebastianTroy** [comment]
You've just referenced two cases where the optimizer handles something, as proof that the optimizer isn't always useful?

I'm making the same argument for capture that has been made for parameter passing. I the author want to program my intent, not fill my code with symbols to handle the exact type shenanigans required to incant it...


On 15 November 2023 15:38:11 Johel Ernesto Guerrero Peña ***@***.***> wrote:

Also this limits capture to copy only, or at least be defined by the author, rather than allow the compiler to decide / optimise.

I recall reading the same comment on Cpp1 lambdas.
As Cpp2 demonstrates, explicit is better than implicit.
There are examples in Cpp1 where "leaving it to the optimizer" has not proven itself for ranges of users.
I recall TDEH<https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#eh-tdeh> and HALO<https://quuxplusone.github.io/blog/2019/08/02/the-tough-guide-to-cpp-acronyms/#halo>.
Please, share the others.

**Comment by JohelEGP** [comment]
> > I'm making the same argument for capture that has been made for parameter passing. I the author want to program my intent, not fill my code with symbols to handle the exact type shenanigans required to incant it...
>
> OK, that's much better.
> In that case, I can get behind the idea of `:(x, in y$ = someReallyLongName) x + y / y ^ y`.

We already have the syntax in Cpp2.
We just need to make the terse forms [the default](https://github.com/hsutter/cppfront/wiki/Design-note%3A-Defaults-are-one-way-to-say-the-same-thing).
See <https://cpp2.godbolt.org/z/7aPcooxjG>:
```Cpp2
main: () = {
  i := 1;
  {  f := :(x) -> _ = { (j := i$) return x + j; };  assert(f(2) == 3);  }
//{  f := :(x)          (j := i$)        x + j;     assert(f(2) == 3);  }
//{  f := :(x) (j := i$) x + j;                     assert(f(2) == 3);  }
  {  f := :() = { (inout j := i&$*) { j++; j++; } };  f();  assert(i == 3);  i = 1;  }
//{  f := :()     (inout j := i&$*) { j++; j++; };    f();  assert(i == 3);  i = 1;  }
//{  f := :() (inout j := i&$*) {
//          j++;
//          j++;
//        };                                          f();  assert(i == 3);  i = 1;  }
  {  f := :() -> forward _ = { (inout j := i&$*) { j++; return j++; } };  assert(f()& == i&);  assert(i == 3);  i = 1;  }
//{  f := :() -> forward _     (inout j := i&$*) { j++; return j++; };    assert(f()& == i&);  assert(i == 3);  i = 1;  }
//{  f := :() -> forward _ (inout j := i&$*) {
//          j++;
//          return j++;
//        };                                                              assert(f()& == i&);  assert(i == 3);  i = 1;  }
}
```
- `:(x) -> _ = { (j := i$) return x + j; }` can be defaulted to
  `:(x)          (j := i$)        x + j;`, and formatted it is
  `:(x) (j := i$) x + j;`.
- `:() = { (inout j := i&$*) { j++; j++; } }` can be defaulted to
  `:()     (inout j := i&$*) { j++; j++; }`, and formatted it is
  `:() (inout j := i&$*) {`
  `  j++;`
  `  j++;`
  `};`.
- `:() -> forward _ = { (inout j := i&$*) { j++; return j++; } }` can be defaulted to
  `:() -> forward _     (inout j := i&$*) { j++; return j++; }`, and formatted it is
  `:() -> forward _ (inout j := i&$*) {`
  `  j++;`
  `  return j++;`
  `};`.

**Comment by JohelEGP** [comment]
That formulation doesn't really work for `copy` parameters.
You make a copy of the actual capture each invocation.
That means that you can actually modify it (i.e., it isn't a member of the function expression object).
See <https://cpp2.godbolt.org/z/Y7a3d5boE>:
```Cpp2
  {  f := :(x) -> _ = { (copy j := i$) return x + j++; };  assert(f(2) == 4);  assert(f(2) == 4);  }
  {  f := :(x)                                x + i$++;    _ = f;                                  }
```

**Comment by JohelEGP** [comment]
Perhaps it'd be better to just allow function expressions to be parameterized just like blocks.
But those parameters appertain to the function expression object.
Note that "function" already implies a function parameter list.
A function expression is a value, and its parameters are part of that value.
So the parameters of a function (which might be an expression)
are different from the parameters of a function expression.
See <https://cpp2.godbolt.org/z/PG4s7GxYY>:
```Cpp2
main: () = {
  i := 1;

  {  f := (copy j := i) :(x) x + j;  assert(f(2) == 3);  }
  {  f := (     j := i) :(x) x + j;  assert(f(2) == 3);  }

  {  f := (inout j := i) :()              = { j++;        j++; };         f();          assert(i == 3);  i = 1;  }
  {  f := (inout j := i) :() -> forward _ = { j++; return j++; };  assert(f()& == i&);  assert(i == 3);  i = 1;  }
}
```

**Comment by AbhinavK00** [comment]
This one is a big change, so I'd really like to hear what Herb has to say and what his rationale was behind the original decision along with if he thinks the change proposed here are worth it.

But since it's the syntax talk, I'll just propose something.
This is something from Hylo. To mark mutation in Hylo, the use a prefixed ampersand like `&var`.
So, a simple way to signal an `inout` capture could be something like `var&$` or `var$&` to signify mutation or address. I know this isn't very far off from the current status quo but it can be explained in a different way.

Also, this idea was originally for marking `inout` call-sites but now the keyword inout is just used there, so I'll just throw it out there.
To mark inout arguments, use `&`
```cpp
a : = 9;
f(x&, 8);  //first argmument is inout
//works very well with UFCS
x&.f(3);
//instead of the current
(inout x).f(7);
```
Making mutation explicit helps and I just think it's a great thing that Hylo has.

_Note_: As for the symbol used, either another symbol could be used (~ comes to mind) or cpp2 can have something different for taking address of a variable (maybe just recommend using std::addressof) or have something similar to sizeof (like `addressof` or `addr`) that just lowers to (preferably) std::addressof. 

Sorry as this got off-topic but just wanted to throw it out there.

**Comment by msadeqhe** [comment]
@JohelEGP I think having one declaration per capture as you have suggested, is the right way. Cpp2 compiler can optimize and avoid the copy by making them a real alias. In a short lambda body, the programmer can directly write `&$*` or `$` in any expression:

```cpp
var1: = 10;

call(: () = {
    print(var1&$* + var1&$*);
});
```

But in a long lambda body, the programmer can optionally make an alias to captures:

```cpp
var1: = 10;

call(: () = {
    // We can use the same variable name `var1`, because it's in a different scope.
    var1: = var1&$*;

    print(var1 + var1);
});
```

Every `var1` in the lambda body will be replaced (similar to a macro) with `var1&$*`, hence they are aliases.

**Comment by msadeqhe** [comment]
If this optimization is not acceptable as the programmer expects `var1` to have its own memory, a new syntax can be used to create aliases. But variable declaration with `==` is `constepxr`, therefore it cannot be used in this case. Is that right?

**Comment by msadeqhe** [comment]
For the alias syntax (in a way that the new name will be replaced with the old name, similar to a macro):

```cpp
abc: namespace     alias = some::long::name;
v32: type          alias = std::vector<i32>;
fnc: (x, y) -> i32 alias = /* any expression */;
var: i32           alias = /* any expression */;
```

`alias` is a contextual keyword. `alias` declarations are similar to namespace, type, function and variable declarations, except when we use them, they will be replaced with their definition, similar to macro.

For example:

```cpp
var1: = 10;
// The type is optional in variable alias declarations.
var2: alias = var1 + 10;

print(var2);
// It generates the following Cpp1 code:
// print(var1 + 10);
```

Or something similar to this approach, to avoid the copy when we declare a variable to capture.

**Comment by msadeqhe** [comment]
```cpp
abc: namespace     alias = some::long::name;
v32: type          alias = std::vector<i32>;
fnc: (x, y) -> i32 alias = /* any expression */;
var: i32           alias = /* any expression */;
```

In this example, function aliases are simply _Forced Inline_ functions. And variable aliases are similar to them.

**Comment by JohelEGP** [comment]
> @JohelEGP I think having one declaration per capture as you have suggested, is the right way.
>
> Cpp2 compiler can optimize and avoid the copy by making them a real alias.

For some context, we're talking about these declarations `j` and `k`:
```Cpp2
  i := 1;
  _ = :() -> _ = {
    j := i&$;
    k := i$;
    return j*++ + k;
  };
```

I did considered this, and thought of two things.

First, the need to prove that it doesn't make a performance difference.
It certainly does for `k`, which is initialized from the capture `i$` each call.

Second, the compiler could recognize that up-front variables are captures.
But that's a semantic change without a change in syntax.
Moving the declaration of `k` after some non-declaration statement still copies each call.

That said, your comment made me think that the status-quo _might_ be fine.
So today you can continue to write (<https://cpp2.godbolt.org/z/aMKnz8PPE>):
```Cpp2
main: () = {
  i := 1;
  (k := i)
    _ = :() -> _ = {
      j := i&$;
      return j*++ + k$;
    };
  (k := i, j := i&)
    _ = :() -> _ = {
      return j$*++ + k$;
    };
}
```
- Alias the variables before capturing them.
- Rely on compiler optimizations for variable declarations in the body.

However, I still think `(copy k := i, j := i&) :()` is strictly superior (<https://github.com/hsutter/cppfront/issues/833#issuecomment-1813072499>):
- SWYM.
- No awkward distance between the block parameters and the function expression
  which might be necessary due to the shape of the code.
- Only this one handles copies of complex expressions well.
  Unless you're OK with writing `k := :() long*.expression()$;` outside and `k$()` inside the function expression.

It looks to me that not having a dedicated place for declaring captures
can lead you to look for workarounds that might not work as you expect.
Specially for copies of complex expressions.
You might want to use those more than once in the body.
The only way to avoid copying twice is as with `k$()` above.

Copies become more important once you can have `this` parameters on function expressions (<https://cpp1.godbolt.org/z/sPhTb9ahr>).
So I think we might really need a solution like <https://github.com/hsutter/cppfront/issues/833#issuecomment-1813072499>.

I certainly like the current status of capturing at the point of use.

**Comment by filipsajdak** [comment]
My favorite `grawlix idiom`

**Comment by wolfseifert** [comment]
Closing in favour of https://github.com/hsutter/cppfront/issues/247.
