### ISSUE TITLE
[BUG] cppfront gives segfault on v2 class with constructor.

### ISSUE THREAD

**Issue by tomFlowee** [hsutter/cppfront#898]
**Describe the bug**

Calling cppfront Digger.cpp2 results in a segfault and an empty cpp file.

**To Reproduce**

Digger.cpp2
```
Digger: type = {
    this: () = {
    }
}
```

`cppfront Digger.cpp2`

I'm probably doing it wrong (wanted to initialize class members there), but I think it should not crash.

**Comment by gregmarr** [comment]
This is the constructor syntax:

```
Digger: type = {
    operator=: (out this) = {
    }
}
```

That code looks like a base member declaration, but it has `()` instead of a name.  It results in this error:
cppfront: source/sema.h:1240: bool cpp2::sema::check(const cpp2::declaration_node&): Assertion `n.is_object()' failed.

I guess the assert should be changed to an error.

**Comment by hsutter** [comment]
Thanks!
