### ISSUE TITLE
[SUGGESTION] Add command-line option to cppfront 

### ISSUE THREAD

**Issue by erasmussen1** [hsutter/cppfront#917]
Add command-line option to cppfront to output include with angle brackets? 

Like this in the to_cpp1.h file.
    _printer.print_extra( "\n#include <cpp2util.h>\n\n" );_

Background:
When creating deb package, it will install the cpp2util.h in the right location and then you can use cppfront anywhere on the machine without copying cpp2util.h file or worry about the right version of cpp2utils.h and etc

**Comment by hsutter** [comment]
Thanks! I'm curious to hear other people's thoughts...?

**Comment by DyXel** [comment]
Hmm, I think it mostly depends on what you want to encourage at this stage :P 

Is binary and/or versioned distribution of cppfront intended, as opposed to distributing source and letting users bootstrap themselves?

Personally, I think such a tiny feature might not hurt if used locally (not for actual packaged distribution, I think its too early maybe), if I am writing tons of tiny programs (hey, its an experiment so that's likely?) in Cpp2 I could see myself not wanting to type in the include flag everywhere and just having a single cpp2util.h I can reference, on the other hand, I have not felt the pain since I just have an one-liner to do the include and compilation automatically. YMMV.

**Comment by hsutter** [comment]
Thinking about usability:

For your use case of creating a package with a single shared cppfront and cpp2util.h, I wonder if you really want to then have to add that option to every cppfront command line? Because if someone forgets it they won't get the shared one.

Or would it work better if cppfront started supporting an environment variable, such as `CPP2FLAGS`? Presumably then you could set it once globally (and/or customized per-user), and then you wouldn't have to add the option to every command line? But then I think you'd also need an opt-out, so something like `-cp[p2util] quotes` / `-cp[p2util] angles` ?

Additional thought: What if it just emitted `<>` always? Is there any reason not to just do that?

**Comment by DyXel** [comment]
> Where I think I'm coming down on is: What if it just emitted <> always? Is there any reason not to just do that? If there is none in a system path it's a no-op, and <> is for headers that are part of the implementation which from cppfront's perspective this is...

Yeah, I think that would be mostly safe? But, do you think you'd need to warn if  the "system" `cpp2util.h` (whatever the compiler actually finds) and the cppfront's build differs? What if, for example, there are some incompatibilities between what the compiler found and what cppfront was expecting, there could be breaking changes that might result in confusing errors, at least that would be my concern with that change.

Side note: What did our forebears do for distribution in general? Maybe we could learn a thing or two on how Bjarne did it for cfront and how the TypeScript folks did it to avoid common pitfalls.

**Comment by gregmarr** [comment]
I'm not sure about this one.  The `""` version should fall back to the locations of the `<>` version, and I'd think you'd WANT to have the local one take precedence if there is one.  I think that would be especially true for the tests.

**Comment by erasmussen1** [comment]
> > Where I think I'm coming down on is: What if it just emitted <> always? Is there any reason not to just do that? If there is none in a system path it's a no-op, and <> is for headers that are part of the implementation which from cppfront's perspective this is...
> 
> Yeah, I think that would be mostly safe? But, do you think you'd need to warn if the "system" `cpp2util.h` (whatever the compiler actually finds) and the cppfront's build differs? What if, for example, there are some incompatibilities between what the compiler found and what cppfront was expecting, there could be breaking changes that might result in confusing errors, at least that would be my concern with that change.
> 
> Side note: What did our forebears do for distribution in general? Maybe we could learn a thing or two on how Bjarne did it for cfront and how the TypeScript folks did it to avoid common pitfalls.

Well, the idea was to put cppfront compiler and the header files in a debian package, so these should not  get out of sync.

In installer will install the cppfront (binary) at 
/usr/local/bin/cppfront 
and the include files in 
/usr/include

and if we have an option for <> the deb installer could create a symlink with this option and all be good.

I guess this request falls just under the category nice to have :)

**Comment by hsutter** [comment]
Based on @gregmarr's good point, I think the current `#include "cpp2util.h"` is correct also for this use case. The meaning isn't defined in the standard, but implementations tend to look in the current directory and fall back to the same directory `#include <cpp2util.h>` would use. So based on that I'll close this for now, but please reopen if I've missed something. Thanks!
